### ISSUE TITLE
[Bug] Xcode 14 build fails with "AppAuth' does not contain bitcode"

### ISSUE THREAD

**Issue by ziobernamac** [firebase/firebase-unity-sdk#461] opened 2022-09-14 08:58 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.40
  * Firebase Unity SDK version: 9.5.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Auth (Auth, Database, etc.)
  * Other Firebase Components in use: Analytics,Messaging,DynamicLinks
  * Additional SDKs you are using: Facebook
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: website

### [REQUIRED] Please describe the issue here:
When Building the app from Xcode 14 (no issue with Xcode 13 and SDK 9.1.0) build fails with this error

'xxxxxxxx/Build/Products/ReleaseForRunning-iphoneos/AppAuth/AppAuth.framework/AppAuth' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file 'xxxxxxxx/Build/Products/ReleaseForRunning-iphoneos/AppAuth/AppAuth.framework/AppAuth' for architecture arm64

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment] 2022-09-14 14:59
Hi @ziobernamac,

Thanks for bringing this to our attention. Based on the information you provided, I'm guessing this issue and [a recent one from the iOS SDK repository](https://github.com/firebase/firebase-ios-sdk/issues/10210) are related due to the specific Xcode version. In order to verify if this is the case, could you provide the complete steps taken to reproduce this behavior?

**Comment by ziobernamac** [comment] 2022-09-14 17:23
I had a Unity project that used Firebase SDK 9.1.0 and with Xcode 13.4 it built correctly.
After upgrading to XCode 14 it started giving that BITCODE error, thinking it might be a compatibility issue with Firebase SDK 9.1.0 i upgraded to 9.5.0, rebuilt the Xcode project from Unity and also in this way it keeps giving this mistake

**Comment by kirand777** [comment] 2022-09-15 07:38
Bitcode has been deprecated in Xcode 14 (see the release notes [here](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes)). If you're building your app via Xcode 14, you can turn off bitcode in your app target.

**Comment by paulinon** [comment] 2022-09-15 13:57
Hi @ziobernamac,

In my first atttempt to reproduce the issue, I've used version 9.5.0 of the SDK in the [quickstart](https://github.com/firebase/quickstart-unity/tree/master/auth/testapp) project, and I haven't encountered the error message you're facing. Are you using this version as well? Could you verify if updating the SDK makes any difference?

You could also try following along @kirand777's suggestion by turning off bitcode in your Xcode build settings.

If neither of these solutions did anything, I'd like you to provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implemetation so we could analyze what's causing the issue

**Comment by ziobernamac** [comment] 2022-09-16 06:01
I apologize for the oversight, I hadn't read that bitcode was deprecated in Xcode14 as correctly reported by @kirand777 , so I'll proceed as per my previous message by deactivating it in the build settings.
Thanks again guys, for the support and sorry if I wasted your time

**Comment by paulinon** [comment] 2022-09-16 08:32
Glad to hear that you've found a solution for your issue, @ziobernamac. That said, I'll be closing this issue.

**Closed by paulinon** 2022-09-16 08:32 UTC
Labels: api: auth, needs-attention, type: question

**Comment by A7medS94** [comment] 2022-09-19 12:02
In build setting search for Enable Bitcode and then set it with "No".

Clean and Build then enjoy!!
