### ISSUE TITLE
[Bug] Unity 6000, Conflicts with AdMob (Unity LevelPlay)

### ISSUE THREAD

**Issue by lordnedox** [firebase/firebase-unity-sdk#1127] opened 2024-10-18 09:40 UTC
### Description

Hi,
I'm getting an error when building the app for Android, using Unity 6000.0.23f1 (LTS). 
The error occurs when using Firebase Analytics in combination with LevelPlay with AdMob enabled.

I've used this same combination with previous version of Unity with no issue (2022.3 worked fine). The error only occurs with the latest version 6000, which is not LTS and the recommeded version to use.

The error is:
Attribute property#android.adservices.AD_SERVICES_CONFIG@resource value=(@xml/ga_ad_services_config) 
	from [com.google.android.gms:play-services-measurement-api:22.1.0] AndroidManifest.xml:32:13-58
	is also present at [com.google.android.gms:play-services-ads-lite:23.4.0] AndroidManifest.xml:109:13-59 value=(@xml/gma_ad_services_config).
	Suggestion: add 'tools:replace="android:resource"' to <property> element at AndroidManifest.xml to override.

I am using latest versions of LevelPlay/AdMob and Firebase Analytics.

I tried adding
<property
            android:name="android.adservices.AD_SERVICES_CONFIG"
            android:resource="@xml/gma_ad_services_config"
            tools:replace="android:resource" />

to the manifest template, but it didn't work, and anyways doesn't seem to be an elegant solution.

Any suggestion?
            

### Reproducing the issue

1. Create a new project with Unity 6000.0.23f1
2. Import Firebase Analytics unity package
3. Import LevelPlay from the Package manager
4. In Mediation configuration, enable AdMob
5. Build the project for Android

### Firebase Unity SDK Version

12.3.0

### Unity editor version

6000.0.23f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Analytics

### Additional SDKs you are using

LevelPlay / AdMob

### Targeted Platform(s)

Android

### Unity editor platform

Windows

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### Relevant Log Output

```shell
GRADLE ERROR : colliding-attributes
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

> Task :launcher:processReleaseMainManifest FAILED
[com.google.firebase:firebase-analytics-unity:12.2.1] 
Warning: Namespace 'com.google.firebase.unity.analytics' is used in multiple modules and/or libraries: 
	com.google.firebase:firebase-analytics-unity:12.2.1, :firebase-analytics-unity-12.2.1:. 
	Please ensure that all modules and libraries have a unique namespace. 
For more information, See https://developer.android.com/studio/build/configure-app-module#set-namespace
See https://developer.android.com/r/studio-ui/build/manifest-merger for more information about the manifest merger.


Attribute property#android.adservices.AD_SERVICES_CONFIG@resource value=(@xml/ga_ad_services_config) 
	from [com.google.android.gms:play-services-measurement-api:22.1.0] AndroidManifest.xml:32:13-58
	is also present at [com.google.android.gms:play-services-ads-lite:23.4.0] AndroidManifest.xml:109:13-59 value=(@xml/gma_ad_services_config).
	Suggestion: add 'tools:replace="android:resource"' to <property> element at AndroidManifest.xml to override.
```

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by damozhang** [comment] 2024-10-19 00:02
same

**Comment by playjoa** [comment] 2024-10-22 00:35
I have the same exact issue here using latest Firebase v12.3.0 (Analytics, Crashanalytics, Auth, FireStore) and AdMob v9.2.1.

@damozhang solution didnt seem to work on my end still can't build for android:

`Error:
	Attribute property#android.adservices.AD_SERVICES_CONFIG@resource value=(@xml/gma_ad_services_config) from [com.google.android.gms:play-services-ads-lite:23.4.0] AndroidManifest.xml:109:13-59
	is also present at [com.google.android.gms:play-services-measurement-api:22.1.0] AndroidManifest.xml:32:13-58 value=(@xml/ga_ad_services_config).
	Suggestion: add 'tools:replace="android:resource"' to <property> element at AndroidManifest.xml to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:processDebugMainManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 3s
]
stdout[

> Configure project :unityLibrary
Variant 'debug', will keep symbols in binaries for:
  'libunity.so'
  'libil2cpp.so'
  'libmain.so'
Variant 'release', symbols will be stripped from binaries.

> Configure project :launcher
Variant 'debug', will keep symbols in binaries for:
  'libunity.so'
  'libil2cpp.so'
  'libmain.so'
Variant 'release', symbols will be stripped from binaries.

> Configure project :unityLibrary:FirebaseApp.androidlib
WARNING: minSdkVersion (23) is greater than targetSdkVersion (9) for variant "debug". Please change the values such that minSdkVersion is less than or equal to targetSdkVersion.
WARNING: minSdkVersion (23) is greater than targetSdkVersion (9) for variant "release". Please change the values such that minSdkVersion is less than or equal to targetSdkVersion.

> Configure project :unityLibrary:FirebaseCrashlytics.androidlib
WARNING: minSdkVersion (23) is greater than targetSdkVersion (9) for variant "debug". Please change the values such that minSdkVersion is less than or equal to targetSdkVersion.
WARNING: minSdkVersion (23) is greater than targetSdkVersion (9) for variant "release". Please change the values such that minSdkVersion is less than or equal to targetSdkVersion.

> Task :unityLibrary:preBuild UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:preDebugBuild UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:preDebugBuild UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:preDebugBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preDebugBuild UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:writeDebugAarMetadata UP-TO-DATE
> Task :unityLibrary:writeDebugAarMetadata UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:writeDebugAarMetadata UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:writeDebugAarMetadata UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateDebugResValues UP-TO-DATE
> Task :unityLibrary:generateDebugResValues UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:generateDebugResValues UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:generateDebugResValues UP-TO-DATE
> Task :unityLibrary:generateDebugResources UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:generateDebugResources UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:generateDebugResources UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:packageDebugResources UP-TO-DATE
> Task :unityLibrary:packageDebugResources UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:packageDebugResources UP-TO-DATE
> Task :unityLibrary:extractDeepLinksDebug UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:extractDeepLinksDebug UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:extractDeepLinksDebug UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:processDebugManifest UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:processDebugManifest UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:compileDebugLibraryResources UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileDebugLibraryResources UP-TO-DATE
> Task :unityLibrary:compileDebugLibraryResources UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:parseDebugLocalResources UP-TO-DATE
> Task :unityLibrary:parseDebugLocalResources UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:parseDebugLocalResources UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:generateDebugRFile UP-TO-DATE
> Task :unityLibrary:generateDebugRFile UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:generateDebugRFile UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:javaPreCompileDebug UP-TO-DATE
> Task :unityLibrary:javaPreCompileDebug UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:javaPreCompileDebug UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateDebugResources
> Task :unityLibrary:mergeDebugShaders UP-TO-DATE
> Task :unityLibrary:compileDebugShaders NO-SOURCE
> Task :unityLibrary:generateDebugAssets UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileDebugJavaWithJavac NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:compileDebugJavaWithJavac NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:bundleLibCompileToJarDebug UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibCompileToJarDebug UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:mergeDebugShaders UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:mergeDebugShaders UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileDebugShaders NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:generateDebugAssets UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:compileDebugShaders NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:generateDebugAssets UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:packageDebugAssets UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:packageDebugAssets UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:processDebugJavaRes NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:processDebugJavaRes NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:mergeDebugJniLibFolders UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:mergeDebugJniLibFolders UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:mergeDebugNativeLibs NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:mergeDebugNativeLibs NO-SOURCE
> Task :unityLibrary:GoogleMobileAdsPlugin.androidlib:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :launcher:preBuild UP-TO-DATE
> Task :launcher:preDebugBuild UP-TO-DATE
> Task :launcher:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :launcher:javaPreCompileDebug UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:packageDebugResources
> Task :unityLibrary:FirebaseCrashlytics.androidlib:extractDeepLinksDebug UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:processDebugManifest UP-TO-DATE
> Task :unityLibrary:processDebugManifest
> Task :unityLibrary:FirebaseCrashlytics.androidlib:javaPreCompileDebug UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileDebugLibraryResources
> Task :unityLibrary:FirebaseCrashlytics.androidlib:mergeDebugShaders UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileDebugShaders NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateDebugAssets UP-TO-DATE
> Task :unityLibrary:packageDebugAssets
> Task :unityLibrary:FirebaseCrashlytics.androidlib:packageDebugAssets UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:processDebugJavaRes NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:mergeDebugJniLibFolders UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:mergeDebugNativeLibs NO-SOURCE
> Task :unityLibrary:processDebugJavaRes UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :unityLibrary:mergeDebugJniLibFolders UP-TO-DATE
> Task :unityLibrary:mergeDebugNativeLibs UP-TO-DATE
> Task :unityLibrary:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:parseDebugLocalResources
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateDebugRFile UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileDebugJavaWithJavac NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:bundleLibCompileToJarDebug UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :launcher:checkDebugAarMetadata UP-TO-DATE
> Task :launcher:generateDebugResValues UP-TO-DATE
> Task :launcher:mapDebugSourceSetPaths
> Task :launcher:generateDebugResources UP-TO-DATE
> Task :launcher:packageDebugResources UP-TO-DATE
> Task :launcher:parseDebugLocalResources UP-TO-DATE
> Task :launcher:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :launcher:extractDeepLinksDebug UP-TO-DATE

> Task :launcher:processDebugMainManifest FAILED
[:googlemobileads-unity:] /Users/joaomilone/.gradle/caches/transforms-3/2adf763a88339aa813b590b6623a66a0/transformed/jetified-googlemobileads-unity/AndroidManifest.xml Warning:
	Namespace 'com.google.unity.ads' is used in multiple modules and/or libraries: :googlemobileads-unity:, :unityLibrary:GoogleMobileAdsPlugin.androidlib. Please ensure that all modules and libraries have a unique namespace. For more information, See https://developer.android.com/studio/build/configure-app-module#set-namespace

See https://developer.android.com/r/studio-ui/build/manifest-merger for more information about the manifest merger.

`

**Comment by RaccoonRecon** [comment] 2024-10-22 09:53
I was having this issue too, it worked to add the following to my manifest:

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
    <application
        <property android:name="android.adservices.AD_SERVICES_CONFIG" android:resource="@xml/ga_ad_services_config" tools:replace="android:resource"/>

**Comment by lordnedox** [comment] 2024-10-25 02:07
> I was having this issue too, it worked to add the following to my manifest:
> 
> `<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools"> <application <property android:name="android.adservices.AD_SERVICES_CONFIG" android:resource="@xml/ga_ad_services_config" tools:replace="android:resource"/>`

Confirmed this workaround works.

**Comment by argzdev** [comment] 2024-10-25 14:11
Hey folks, thanks for reaching out. I was able to reproduce this behavior in the native Firebase Android SDK. Adding the following dependency triggers this issue.
```
implementation("com.google.firebase:firebase-analytics:22.1.2")
implementation("com.google.android.gms:play-services-ads:23.4.0")
```

The issue is due to the transient dependency of Firebase and Admob. The stacktrace shows that these libraries are causing the conflict:
```
com.google.android.gms:play-services-measurement-api:22.1.2
com.google.android.gms:play-services-ads-lite:23.4.0
```

Both of which are libraries from the Google Play Services. A discussion with the AGP team in the public bug link: https://issuetracker.google.com/issues/327696048 determines that these dependencies has to fix it on their side. Once those fixes are applied, it will then trickle down to our SDKs.

There's not much we can do on our SDK since it is only grabbing those dependencies. I'd recommend following up on the public bug link to get feedback. I'll go ahead and close this thread.

**Closed by argzdev** 2024-10-25 14:11 UTC
Labels: api: analytics, type: bug
