### ISSUE TITLE
[Question] FirebaseCppApp-9_1_0 DLL not found when there's no C++ Redistributable.

### ISSUE THREAD

**Issue by pabloleban** [firebase/firebase-unity-sdk#385] opened 2022-06-27 02:39 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: Unity 2020.3.34f1
  * Firebase Unity SDK version: 9.1.0
  * Source you installed the SDK: Unity Package Manager (tarball)
  * Problematic Firebase Component: Firebase App (Core)
  * Other Firebase Components in use: Storage, Auth, Crashlytics
  * Additional SDKs you are using: Yodo1 MAS SDK
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Windows
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: No

### [REQUIRED] Please describe the question here:
**Some** users which don't have C++ Redistributable are getting this issue printed in their Player.log and Firebase can't be initialized.

```
DllNotFoundException: Unable to load DLL 'FirebaseCppApp-9_1_0': The specified module could not be found.
  at Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () [0x00000] in <00000000000000000000000000000000>:0 
  at Firebase.AppUtilPINVOKE..cctor () [0x00000] in <00000000000000000000000000000000>:0 
  at Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) [0x00000] in <00000000000000000000000000000000>:0 
  at Firebase.LogUtil..cctor () [0x00000] in <00000000000000000000000000000000>:0 
  at Firebase.FirebaseApp..cctor () [0x00000] in <00000000000000000000000000000000>:0 
  at FirebaseInitializer.Awake () [0x00000] in <00000000000000000000000000000000>:0 
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE.SWIGExceptionHelper' threw an exception.
  at Firebase.AppUtilPINVOKE..cctor () [0x00000] in <00000000000000000000000000000000>:0 
  at Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) [0x00000] in <00000000000000000000000000000000>:0 
  at Firebase.LogUtil..cctor () [0x00000] in <00000000000000000000000000000000>:0 
  at Firebase.FirebaseApp..cctor () [0x00000] in <00000000000000000000000000000000>:0 
  at FirebaseInitializer.Awake () [0x00000] in <00000000000000000000000000000000>:0 
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
  at Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) [0x00000] in <00000000000000000000000000000000>:0 
  at Firebase.LogUtil..cctor () [0x00000] in <00000000000000000000000000000000>:0 
  at Firebase.FirebaseApp..cctor () [0x00000] in <00000000000000000000000000000000>:0 
  at FirebaseInitializer.Awake () [0x00000] in <00000000000000000000000000000000>:0 
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
  at Firebase.FirebaseApp..cctor () [0x00000] in <00000000000000000000000000000000>:0 
  at FirebaseInitializer.Awake () [0x00000] in <00000000000000000000000000000000>:0 
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
  at FirebaseInitializer.Awake () [0x00000] in <00000000000000000000000000000000>:0 

DllNotFoundException: Unable to load DLL 'FirebaseCppApp-9_1_0': The specified module could not be found.
  at Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) [0x00000] in <00000000000000000000000000000000>:0 
  at Firebase.LogUtil.Finalize () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
System.Xml.Serialization.XmlElementEventHandler:Invoke(Object, XmlElementEventArgs)
```

However the DLL can still be found in the game files, so why can't be loaded if they don't have C++ redistributable?
Is this an intended behaviour?

**Comment by a-maurice** [comment] 2022-06-28 17:52
This is intended behavior.  The Firebase Unity SDK does use a C++ layer across all platforms, so on Windows if they do not have the C++ redistributable, then they would fail to be able to call into the library.  I assume that is why the error says it fails to find the dll, because it can't load it correctly.

Thanks for flagging this, I'm going to close this issue for now, but we will see about improving our documentation to make this dependency more apparent.

**Closed by a-maurice** 2022-06-28 17:52 UTC
Labels: api: core, type: question, desktop support

**Comment by fmoyano** [comment] 2022-07-15 11:14
> This is intended behavior. The Firebase Unity SDK does use a C++ layer across all platforms, so on Windows if they do not have the C++ redistributable, then they would fail to be able to call into the library. I assume that is why the error says it fails to find the dll, because it can't load it correctly.
> 
> Thanks for flagging this, I'm going to close this issue for now, but we will see about improving our documentation to make this dependency more apparent.

Thanks, this solved the issue, but I wonder: why didn't it happen in previous versions of Firebase? Just out of curiosity...
