### ISSUE TITLE
[Bug] Firebase.AppUtilPINVOKE.PollCallbacks causes unity crash

### ISSUE THREAD

**Issue by GabrielJadderson** [firebase/firebase-unity-sdk#784] opened 2023-07-06 13:09 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.45f
  * Firebase Unity SDK version: 11.2
  * Source you installed the SDK: upm
  * Problematic Firebase Component: Platform
  * Other Firebase Components in use: Platform
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Windows 
  * Platform you are targeting: Android & iOS
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Pre-built SDK

### [REQUIRED] Please describe the issue here:

Unity crashes randomly while compiling scripts. Happens very very often atleast once an hour.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
100%

What happened? How can we make the problem occur?
just write some code and wait for unity to compile then it will crash randomly. 

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

Stacktrace of the error, It's always the same stacktrace.
 
![image](https://github.com/firebase/firebase-unity-sdk/assets/1836034/7f0f8299-fe13-48b3-a9c0-3f487f3d45d4)

**Comment by jonsimantov** [comment] 2023-07-06 20:41
Which Firebase products have you imported into your Unity project?

**Comment by GabrielJadderson** [comment] 2023-07-07 10:07
![image](https://github.com/firebase/firebase-unity-sdk/assets/1836034/f43e63f9-60d5-4fb7-9595-0a83288ef5a9)

**Comment by cometa93** [comment] 2023-07-07 11:47
Same...
https://github.com/firebase/firebase-unity-sdk/issues/777

**Comment by GabrielJadderson** [comment] 2023-07-07 13:39
downgrading does not fix the issue for us.

**Comment by jonsimantov** [comment] 2023-07-11 21:28
This appears to be a duplicate of #777.

**Closed by jonsimantov** 2023-07-11 21:28 UTC
Labels: type: question, unity-editor

**Comment by GabrielJadderson** [comment] 2023-08-02 12:46
The error happens in this dll "FirebaseCppApp-11_2_0" the entrypoint is in this function "Firebase_App_CSharp_PollCallbacks"
