### ISSUE TITLE
[Bug] Apple Sign In with Android can sometimes freeze the app

### ISSUE THREAD

**Issue by maxgmer** [firebase/firebase-unity-sdk#1043] opened 2024-06-06 11:19 UTC
### Description

Expected:
1. I launch the sign-in with Apple flow on android.
2. I go through the webview, complete Apple ID authentication.
3. I'm redirected back to the app, Firebase sign-in operation finishes and the logic continues.
Or, I'm redirected back to the app and the app is relaunched (in case OS killed the process).
Freezing shouldn't happen in both cases.

Happening currently:
1. I launch the sign-in with Apple flow on android.
2. I go through the webview, complete Apple ID authentication.
3. I'm redirected back to the app, which freezes. Then OS offers to force quit the app.

### Reproducing the issue

~~Reproducible in 100% of attempts, at least for me.~~

~~1. Make sure this is a first sign-in. If not, delete Apple ID for the app on your IPhone in Apple ID dashboard, "Sign in with Apple" button and delete the Firebase user.
2. Open the app with Firebase Apple Sign in on Android.
3. Start the sign-in flow, go through it until you are redirected back to the app.
4. Boom, you are redirected into a frozen app.~~

~~P.S. don't be too slow with sign-in, because Android OS will kill the Unity process. If it does, the app will be relaunched and you will log in successfully, because it won't be your first sign-in anymore.~~

**UPD**: After doing a couple more tests, I couldn't reproduce once, probably the steps are wrong.
The issue seems kind of random and not always reproducible. Also happens during any apple sign-in, not just the first one.

But it happens VERY often, so just try a couple of times.

### Firebase Unity SDK Version

11.9.0

### Unity editor version

2023.2.20f1

### Installation Method

Unity Package Manager

### Problematic Firebase Component(s)

Authentication

### Other Firebase Component(s) in use

Analytics, Crashlytics

### Additional SDKs you are using

None

### Targeted Platform(s)

Android

### Unity editor platform

Mac

### Scripting Runtime

IL2CPP

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by maxgmer** [comment] 2024-06-07 08:55
Not sure if it's useful, but here are the logs of the ANR from Crashlytics:
<img width="1350" alt="Screenshot 2024-06-07 at 11 53 40" src="https://github.com/firebase/firebase-unity-sdk/assets/24964174/77f7899b-883c-4d0a-83aa-9bd6f8f54a67">

          main (native):tid=1 systid=12168 
#00 pc 0x88270 libc.so (syscall + 32) (BuildId: 2f84be24a19d511a358a9050af5b3974)
#01 pc 0x8cb3c libc.so (__futex_wait_ex + 148) (BuildId: 2f84be24a19d511a358a9050af5b3974)
#02 pc 0xf0020 libc.so (pthread_cond_wait + 84) (BuildId: 2f84be24a19d511a358a9050af5b3974)
#03 pc 0x2f6bc libgame.so (onResume + 144) (BuildId: f5869e5e92b126c2fe4bcaa0aa229e0a61d3165e)
#04 pc 0x355830 libart.so (art_quick_generic_jni_trampoline + 144) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#05 pc 0x33eda4 libart.so (art_quick_invoke_stub + 612) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#06 pc 0x511050 libart.so (bool art::interpreter::DoCall<false> + 1976) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#07 pc 0x4973dc libart.so (void art::interpreter::ExecuteSwitchImplCpp<false> + 960) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#08 pc 0x357fd8 libart.so (ExecuteSwitchImplAsm + 8) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#09 pc 0x474c3c base.apk (com.google.androidgamesdk.GameActivity.onResume)
#10 pc 0x374120 libart.so (art::interpreter::Execute  + 232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#11 pc 0x511d1c libart.so (bool art::interpreter::DoCall<false> + 5252) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#12 pc 0x49774c libart.so (void art::interpreter::ExecuteSwitchImplCpp<false> + 1840) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#13 pc 0x357fd8 libart.so (ExecuteSwitchImplAsm + 8) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#14 pc 0x1548 base.apk (com.unity3d.player.UnityPlayerGameActivity.onResume)
#15 pc 0x374120 libart.so (art::interpreter::Execute  + 232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#16 pc 0x511d1c libart.so (bool art::interpreter::DoCall<false> + 5252) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#17 pc 0x4973dc libart.so (void art::interpreter::ExecuteSwitchImplCpp<false> + 960) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#18 pc 0x357fd8 libart.so (ExecuteSwitchImplAsm + 8) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#19 pc 0x22eea0 framework.jar (android.app.Instrumentation.callActivityOnResume)
#20 pc 0x374120 libart.so (art::interpreter::Execute  + 232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#21 pc 0x511d1c libart.so (bool art::interpreter::DoCall<false> + 5252) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#22 pc 0x4973dc libart.so (void art::interpreter::ExecuteSwitchImplCpp<false> + 960) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#23 pc 0x357fd8 libart.so (ExecuteSwitchImplAsm + 8) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#24 pc 0x1bb714 framework.jar (android.app.Activity.performResume)
#25 pc 0x374120 libart.so (art::interpreter::Execute  + 232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#26 pc 0x511d1c libart.so (bool art::interpreter::DoCall<false> + 5252) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#27 pc 0x4973dc libart.so (void art::interpreter::ExecuteSwitchImplCpp<false> + 960) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#28 pc 0x357fd8 libart.so (ExecuteSwitchImplAsm + 8) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#29 pc 0x1ab510 framework.jar (android.app.ActivityThread.performResumeActivity)
#30 pc 0x374120 libart.so (art::interpreter::Execute  + 232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#31 pc 0x511d1c libart.so (bool art::interpreter::DoCall<false> + 5252) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#32 pc 0x4973dc libart.so (void art::interpreter::ExecuteSwitchImplCpp<false> + 960) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#33 pc 0x357fd8 libart.so (ExecuteSwitchImplAsm + 8) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#34 pc 0x1b1b4c framework.jar (android.app.ActivityThread.handleResumeActivity)
#35 pc 0x374120 libart.so (art::interpreter::Execute  + 232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#36 pc 0x511d1c libart.so (bool art::interpreter::DoCall<false> + 5252) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#37 pc 0x4973dc libart.so (void art::interpreter::ExecuteSwitchImplCpp<false> + 960) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#38 pc 0x357fd8 libart.so (ExecuteSwitchImplAsm + 8) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#39 pc 0x2ba7e0 framework.jar (android.app.servertransaction.ResumeActivityItem.execute)
#40 pc 0x374120 libart.so (art::interpreter::Execute  + 232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#41 pc 0x511d1c libart.so (bool art::interpreter::DoCall<false> + 5252) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#42 pc 0x4973dc libart.so (void art::interpreter::ExecuteSwitchImplCpp<false> + 960) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#43 pc 0x357fd8 libart.so (ExecuteSwitchImplAsm + 8) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#44 pc 0x2b78d4 framework.jar (android.app.servertransaction.ActivityTransactionItem.execute)
#45 pc 0x374120 libart.so (art::interpreter::Execute  + 232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#46 pc 0x511d1c libart.so (bool art::interpreter::DoCall<false> + 5252) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#47 pc 0x4973dc libart.so (void art::interpreter::ExecuteSwitchImplCpp<false> + 960) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#48 pc 0x357fd8 libart.so (ExecuteSwitchImplAsm + 8) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#49 pc 0x2bb89c framework.jar (android.app.servertransaction.TransactionExecutor.executeLifecycleState)
#50 pc 0x374120 libart.so (art::interpreter::Execute  + 232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#51 pc 0x511d1c libart.so (bool art::interpreter::DoCall<false> + 5252) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#52 pc 0x497814 libart.so (void art::interpreter::ExecuteSwitchImplCpp<false> + 2040) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#53 pc 0x357fd8 libart.so (ExecuteSwitchImplAsm + 8) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#54 pc 0x2bb6ec framework.jar (android.app.servertransaction.TransactionExecutor.execute)
#55 pc 0x374120 libart.so (art::interpreter::Execute  + 232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#56 pc 0x511d1c libart.so (bool art::interpreter::DoCall<false> + 5252) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#57 pc 0x4973dc libart.so (void art::interpreter::ExecuteSwitchImplCpp<false> + 960) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#58 pc 0x357fd8 libart.so (ExecuteSwitchImplAsm + 8) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#59 pc 0x1a7f74 framework.jar (android.app.ActivityThread$H.handleMessage)
#60 pc 0x374120 libart.so (art::interpreter::Execute  + 232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#61 pc 0x511d1c libart.so (bool art::interpreter::DoCall<false> + 5252) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#62 pc 0x4973dc libart.so (void art::interpreter::ExecuteSwitchImplCpp<false> + 960) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#63 pc 0x357fd8 libart.so (ExecuteSwitchImplAsm + 8) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#64 pc 0x4345e0 framework.jar (android.os.Handler.dispatchMessage)
#65 pc 0x374120 libart.so (art::interpreter::Execute  + 232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#66 pc 0x511d1c libart.so (bool art::interpreter::DoCall<false> + 5252) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#67 pc 0x4973dc libart.so (void art::interpreter::ExecuteSwitchImplCpp<false> + 960) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#68 pc 0x357fd8 libart.so (ExecuteSwitchImplAsm + 8) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#69 pc 0x45f280 framework.jar (android.os.Looper.loopOnce)
#70 pc 0x374120 libart.so (art::interpreter::Execute  + 232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#71 pc 0x511d1c libart.so (bool art::interpreter::DoCall<false> + 5252) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#72 pc 0x49774c libart.so (void art::interpreter::ExecuteSwitchImplCpp<false> + 1840) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#73 pc 0x357fd8 libart.so (ExecuteSwitchImplAsm + 8) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#74 pc 0x45fa08 framework.jar (android.os.Looper.loop)
#75 pc 0x374120 libart.so (art::interpreter::Execute  + 232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#76 pc 0x511d1c libart.so (bool art::interpreter::DoCall<false> + 5252) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#77 pc 0x49774c libart.so (void art::interpreter::ExecuteSwitchImplCpp<false> + 1840) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#78 pc 0x357fd8 libart.so (ExecuteSwitchImplAsm + 8) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#79 pc 0x1b3054 framework.jar (android.app.ActivityThread.main)
#80 pc 0x374120 libart.so (art::interpreter::Execute  + 232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#81 pc 0x373a18 libart.so (artQuickToInterpreterBridge + 964) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#82 pc 0x355968 libart.so (art_quick_to_interpreter_bridge + 88) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#83 pc 0x33f080 libart.so (art_quick_invoke_static_stub + 640) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#84 pc 0x3884dc libart.so (_jobject* art::InvokeMethod<8> + 1588) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#85 pc 0x387e98 libart.so (art::Method_invoke  + 32) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#86 pc 0x355830 libart.so (art_quick_generic_jni_trampoline + 144) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#87 pc 0x33eda4 libart.so (art_quick_invoke_stub + 612) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#88 pc 0x511050 libart.so (bool art::interpreter::DoCall<false> + 1976) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#89 pc 0x4973dc libart.so (void art::interpreter::ExecuteSwitchImplCpp<false> + 960) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#90 pc 0x357fd8 libart.so (ExecuteSwitchImplAsm + 8) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#91 pc 0x292ca4 framework.jar (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run)
#92 pc 0x374120 libart.so (art::interpreter::Execute  + 232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#93 pc 0x373a18 libart.so (artQuickToInterpreterBridge + 964) (BuildId: 735f12f804f88d62a2cb437261076ff7)
#94 pc 0x355968 libart.so (art_quick_to_interpreter_bridge + 88) (BuildId: 735f12f804f88d62a2cb437261076ff7)
       at com.google.androidgamesdk.GameActivity.onResumeNative(Native method)
       at com.google.androidgamesdk.GameActivity.onResume(GameActivity.java:394)
       at com.unity3d.player.UnityPlayerGameActivity.onResume(UnityPlayerGameActivity.java:114)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1477)
       at android.app.Activity.performResume(Activity.java:8323)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4907)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4950)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8319)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

**Comment by maxgmer** [comment] 2024-06-07 09:34
Couldn't reproduce in production builds at all (if I can, I'll comment here/reopen a new issue).

Seems like when this error happens in prod builds, the app just restarts successfully (which is fine, OS kills the process all the time as well anyways).

@argzdev You can close this issue or you can leave it in low priority, if you want to fix it development builds.

**Comment by argzdev** [comment] 2024-06-10 09:30
Hey @maxgmer, thanks for all these details. We'll try to look into this and check if there's an issue. Thanks!

**Comment by argzdev** [comment] 2024-06-28 10:32
Hi @maxgmer, after further testing I'm still unable to reproduce the same behavior with any iOS versions on simulators. The issue might be due to something else entirely. I'll go ahead and close this thread for now. Feel free to come back here or reopen a new thread if in case the issue arises again. Thanks!

**Closed by argzdev** 2024-06-28 10:32 UTC
Labels: api: auth
