### ISSUE TITLE
iOS Storage reads are never Auth'd

### ISSUE THREAD

**Issue by pabloleban** [firebase/firebase-unity-sdk#133] opened 2021-12-13 13:51 UTC
Some users (included me) are still getting this error. It makes Firebase Storage unusable and it has been around for 4 months.
It's stopping me from upgrading to the last version and I'm still using 7.2.0 because of that.

Update: After some testing, I can see that it works fine when you use the quickstart auth + storage on a clean project. So maybe this is a bug that happens only when you migrate from 7.x (in my case 7.2.0) to newer versions, but I still have to do some more tests.

**Comment by BlackSp1der** [comment] 2022-02-02 00:45
Hi, I am also unable to read data storage when the auth conditional rule is enabled. I just updated firebase to the latest version 8.8.0 and the issue is still there. I am going to try 7.2.0. I wonder why there are no more reports about this, looks like some devs just opt to use public access and don't care to protect user data.

**Comment by steve6t6** [comment] 2022-02-07 10:35
Hello, we encountered this issue when upgrading from Firebase 7.2.0 to 8.1.0. 
On iOS exclusively trying to get file from Storage we get  "User is not authorized to perform the desired action" error. 
We commented on this thread: https://github.com/firebase/quickstart-unity/issues/1115 But this thread appears to have died also. 

We want to upgrade the SDK to make use of new features, but simply cannot as it breaks our app for our iOS clients.

**Comment by parsoyaarihant** [comment] 2022-02-11 12:31
Same issue here, have been stuck on this issue for months. I find it hard to believe that Firebase team haven't resolved this issue so far.

**Comment by steve6t6** [comment] 2022-02-16 13:50
Just did a test upgrade to 8.8.0 and the error persists.

**Comment by npicouet** [comment] 2022-02-24 18:12
Hey there! Glad someone else made an issue. I keep posting about it, it has been ongoing for 5-6 months now and is a HUGE issue. Literally just broken right now! Please prioritize a fix for this.

**Comment by a-maurice** [comment] 2022-04-08 00:27
Hi all,

I messaged on the other ticket, but to also post here, we've been struggling to reproduce this issue. We did recently ship a new version, 8.9.0, which contains a fix to EDM4U, the tool we use to manage iOS dependencies, to properly handle source Cocoapods. I'm not sure if that will resolve the problem though, as we haven't been able to reproduce it on older versions either.

To confirm, this only seems to be happening on Read, not on Write?

**Comment by BlackSp1der** [comment] 2022-04-11 00:21
Hi, this happens when you read or write, it depends on the rule. maybe you did not add it to your test environment.
something like this:

rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /user_data/{userId}/{allPaths=**} {
     allow read, write: if (request.auth != null) && (request.auth.uid == userId)
    }
  }
}

so, only the owner (userID) can change the data. but this doesn't work, looks like the auth user ID is not stored in the session when you try to access your data. if we remove the auth validation it works.

**Comment by pabloleban** [comment] 2022-04-16 14:38
So I've been trying to replicate this issue in a new empty project but I was unable to do so. It works completely fine there with 8.9.0. I'll try to do the same migration (from 7.2.0 to 8.9.0) in that same project and see if the problem is there.

**Comment by erikhallgren** [comment] 2022-04-24 14:05
@a-maurice I can confirm having this issue only with read, writing is fine and works as expected

**Comment by a-maurice** [comment] 2022-05-19 23:15
We've released a new version of the Firebase for Unity SDK, 9.0.0, available here: https://github.com/firebase/firebase-unity-sdk/releases/tag/v9.0.0, that includes the fix for this.

The problem seems to have been in how the C++ SDK was interacting with the iOS SDK, but the iOS SDK was rewritten into swift, so there isn't a PR on the Unity side that reflects the fix, but from personal testing, I wasn't able to reproduce it after updating. Thanks for flagging this, and sorry it took a while to fix.

**Closed by a-maurice** 2022-05-19 23:16 UTC
