### ISSUE TITLE
[Bug] Editor crash when Firestore "CollectionReference usersRef = db.Collection("users")"/ "DocumentRefrence" calls

### ISSUE THREAD

**Issue by deveshbeniwal** [firebase/firebase-unity-sdk#381] opened 2022-06-25 08:07 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: ___2021.3.2f1
  * Firebase Unity SDK version: ___9.1.0
  * Source you installed the SDK: ___FirebaseFirestore (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: ___Firestore (Auth, Database, etc.)
  * Other Firebase Components in use: ___none (Auth, Database, etc.)
  * Additional SDKs you are using: ___none (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: ___Windows (Mac, Windows, or Linux)
  * Platform you are targeting: ___Android (iOS, Android, and/or desktop)
  * Scripting Runtime: ___Mono (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity)

### [REQUIRED] Please describe the issue here:

When we initialize CollectionReference or DocumentReference unity editor crashed! 
Firebase initialization is working when the Auth is working fine and initializing of firestore is fine too! But when we write line
**"CollectionReference usersRef = db.Collection("users")" or "DocumentReference docRef = db.Collection("users").Document("xyz");"
It crash immediately.** 
Crash log - https://drive.google.com/file/d/1XkGgwH9UuiNp4Jz9UZaLDt7Wv5T_8CBQ/view?usp=sharing

I tried downgrading sdk changing unity versions too! But no luck

#### Steps to reproduce:

1. New empty project created.
2. Imported firestore package
3. added google service file
4. firestore instance created
5. Try to read data from collection
6. CRASHED!

In my system issue repro rate is 100%

#### Relevant Code:

NOTE : ReadData method calls over a button

```
    FirebaseFirestore db;
    void Start()
    {
        db = FirebaseFirestore.DefaultInstance;
    }
    public void ReadData()
    {
        DocumentReference docRef = db.Collection("users").Document("xyz");
        CollectionReference usersRef = db.Collection("users");
        usersRef.GetSnapshotAsync().ContinueWithOnMainThread(task =>
        {
            QuerySnapshot snapshot = task.Result;
            foreach (DocumentSnapshot document in snapshot.Documents)
            {
                Debug.Log(String.Format("User: {0}", document.Id));
                Dictionary<string, object> documentDictionary = document.ToDictionary();
                Debug.Log(String.Format("First: {0}", documentDictionary["First"]));
                if (documentDictionary.ContainsKey("Middle"))
                {
                    Debug.Log(String.Format("Middle: {0}", documentDictionary["Middle"]));
                }

                Debug.Log(String.Format("Last: {0}", documentDictionary["Last"]));
                Debug.Log(String.Format("Born: {0}", documentDictionary["Born"]));
            }

            Debug.Log("Read all data from the users collection.");
        });
    }
```

**Comment by dconeybe** [comment] 2022-06-25 13:25
This is a duplicate of https://github.com/firebase/quickstart-unity/issues/1284. 

For reference, here is the stack trace:
```
0x00007FFD58ED998D (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58EDAE9B (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58ED6D21 (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58ED78F0 (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58ED7BB2 (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58ECB383 (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58ED08DE (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58ECF730 (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58ECF980 (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58EBBF32 (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58E70B40 (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58E7B532 (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58E7CDCA (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58DF8C6E (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58E428C9 (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58DE5A0A (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58EFB168 (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58F0125D (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58EF9158 (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD58EF8374 (FirebaseCppApp-8_10_0) uWS::HttpSocket<0>::upgrade
0x00007FFD73F41BB2 (ucrtbase) configthreadlocale
0x00007FFD75A07034 (KERNEL32) BaseThreadInitThunk
0x00007FFD76042651 (ntdll) RtlUserThreadStart
```

**Closed by dconeybe** 2022-06-25 13:25 UTC
Labels: new, type: question

**Comment by deveshbeniwal** [comment] 2022-06-28 05:08
@dconeybe Got the solution! Unity project is making multiple instances for firestore or realtime database so we have to make it persistant after taking instance. You can declare instance like below - 

        db = FirebaseFirestore.DefaultInstance;
        db.Settings.PersistenceEnabled = false;

NOTE : PersistenceEnabled must be false.
Also this error might thorugh from firebase while we initialize instance. HOPE this will be get solved in next updates
