### ISSUE TITLE
Sms is not receiving from Firebase 

### ISSUE THREAD

**Issue by CLOUDFIRE91** [firebase/firebase-unity-sdk#712] opened 2023-05-08 12:10 UTC
Hi All 

I am using unity  2019.4.40 . and i am  using unity quick start master   and i have downloaded  Firebase_unity_sdk_9.4.0...

I have added Sha1 and Sha 256  in Firebase console. i have downloaded googleservies.json file from Firebase  console. 

when i enter my phone number and click authenticate code. Nothing happens. No message is  there.  Sms is not receiving from 

firebase. So whats the problem. I have using this project for past 1.5 years. It is everything works fine . But past 2  months it is not 

working.  So whats the problem. Did i have to change any settings from  firebase. or there is any update happen in firebase ???

So kindly check ur side also. whether ur receving sms also. ?Kindly do the needful..

**Comment by chkuang-g** [comment] 2023-05-08 19:09
Could you try to follow our issue template for more information?
Thank you

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____
  * Firebase Unity SDK version: _____
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by CLOUDFIRE91** [comment] 2023-05-09 04:50
Unity editor version: Unity 2019.4.40

Firebase Unity SDK version: Firebase_unity_sdk 9.4.0

Problematic Firebase Component: Auth

Other Firebase Components in use: None(only auth)

Additional SDKs you are using:None(only auth)

Platform you are using the Unity editor on: Windows

Platform you are targeting: Android

Scripting Runtime:Mono

Pre-built SDK from the website :Firebase_unity_sdk 9.4.0


Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)  1

What happened? How can we make the problem occur?

I have enabled Shal1 and Sha256 in firebase console.I have downloaded the google json file from firebase. and put it in Assets/StreamingAssets. I have donwloaded  quickstart-unity master and installed auth(Firebase_unity_sdk 9.4.0).
When i clicked the authenticate phone number. It Said Phone Auth, Code Sent . But Sms is not received from firebase.
i clicked mutliple times. it said phone code sent. but i did not received sms. My APP is in PLAYSTORE. users are not getting sms. 
Kindly check the Quick Start master project also. I think there is a bug . Kindly do the needful. 
SMS is not receving from Firebase.

**Comment by paulinon** [comment] 2023-05-09 14:58
Hi @CLOUDFIRE91,

Thanks for the report. I've recently used the quickstart, and I was able to retrieve an OTP. I'd like you to try the following:
- Update the Firebase SDK to its latest version (10.7.0 as of writing).
- Place your `google-services.json` file just in the Assets folder.
- Try downloading a new `google-services.json` file for your implementation.

If none of these steps resolved your issue, then the cause of this behavior may lie within your backend. You may reach out to [Firebase Support](https://firebase.google.com/support) where one of our agents can help you out. You may reference this ticket as well as provide any relevant information to your project there. That said, I'll be closing this for now.

**Closed by paulinon** 2023-05-09 14:58 UTC
Labels: needs-attention, type: question
