### ISSUE TITLE
[Bug] Unable to find Method com/google/firebase/remoteconfig/ConfigUpdateListenerRegistration.remove

### ISSUE THREAD

**Issue by lagoonbbbo** [firebase/firebase-unity-sdk#753] opened 2023-06-05 10:58 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.24f1
  * Firebase Unity SDK version: 11.1.0
  * Source you installed the SDK: .tgz
  * Problematic Firebase Component: remote config
  * Other Firebase Components in use: messaging, analytics
  * Additional SDKs you are using: Google Play AppUpdate, AppBundle, AssetDelivery, InAppReview
  * Platform you are using the Unity editor on: Windows/Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: prebuilt

### [REQUIRED] Please describe the issue here:

Since the v11.0 upgrade when I launch the app and try to access FirebaseRemoteConfig.DefaultInstance, I have the following warning on the logcat console:
java.lang.NoSuchMethodError: no non-static method "Lcom/google/firebase/remoteconfig/ConfigUpdateListenerRegistration;.remove()V"

followed by the error:
Unable to find Method com/google/firebase/remoteconfig/ConfigUpdateListenerRegistration.remove (signature '()V', instance).  Please verify the AAR which contains the com/google/firebase/remoteconfig/ConfigUpdateListenerRegistration class is included in your app.

What's the issue repro rate? 100%

using Firebase version 10.7.0 everything works as expected.

#### Relevant Code:

```csharp
FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => 
{
    var dependencyStatus = task.Result;
    if( dependencyStatus == DependencyStatus.Available ) 
    {
        // this log appear in the console
        Debug.Log( $"RemoteConfig --- FIREBASE CheckAndFixDependenciesAsync complete. {task.Result}" );

        // Create and hold a reference to your FirebaseApp,
        // where app is a Firebase.FirebaseApp property of your application class.
        FirebaseAppInstance = FirebaseApp.DefaultInstance;

        
        // Apply RemoteConfig default values
        FirebaseRemoteConfig.DefaultInstance.SetDefaultsAsync( DefaultValues ).ContinueWithOnMainThread( _ =>
        {
           // This log never appear in the console
           Debug.Log( "FIREBASE SetDefaultsAsync complete." );
            
            // Get config from Firebase
            FirebaseRemoteConfig.DefaultInstance.FetchAndActivateAsync().ContinueWithOnMainThread( _ =>
            {
                var remoteConfig = FirebaseRemoteConfig.DefaultInstance;
                var info         = remoteConfig.Info;
                
                // TODO get values from RemoteConfig
            } );
        } );
    } 
    else 
    {
        Debug.LogError( $"Could not resolve all Firebase dependencies: {dependencyStatus}" );
        // Firebase Unity SDK is not safe to use here.
    }
});
```

see attached my mainTemplate.gradle file
[mainTemplate.gradle.txt](https://github.com/firebase/firebase-unity-sdk/files/11651786/mainTemplate.gradle.txt)

**Comment by lagoonbbbo** [comment] 2023-06-14 05:18
Hi, I just created a new Unity project, imported the packages and the same bug is present.
Here is the sample project, I removed the Library to be smaller, and the google-info.json as it's private. I also removed the .tgz files, just add them in the PKGS directory:
 - com.google.firebase.analytics-11.1.0.tgz
 - com.google.firebase.app-11.1.0.tgz
 - com.google.firebase.messaging-11.1.0.tgz
 - com.google.firebase.remote-config-11.1.0.tgz
 - com.google.external-dependency-manager-1.2.176.tgz
[RemoteConfigBug_Project.zip](https://github.com/firebase/firebase-unity-sdk/files/11741887/RemoteConfigBug_Project.zip)

**Comment by paulinon** [comment] 2023-06-14 14:54
Thanks for the additional information, @lagoonbbbo. I was able to encounter the logs that you described using your sample project, and I'll be relaying my observations to the team. You may refer to this thread for any updates. I'll be marking this as a bug for now.

**Comment by a-maurice** [comment] 2023-06-14 21:52
Hi @lagoonbbbo 

Thanks for the bug report.  The problem is that the symbols are being stripped by minification.  We will try to get this fixed in the next release, but in the meantime, a pretty simple workaround is available.

In your `Assets/Plugins/Android/proguard-user.txt` file, you can add:
```
-keep,includedescriptorclasses public class com.google.firebase.remoteconfig.ConfigUpdateListenerRegistration { *; }
```

**Comment by lagoonbbbo** [comment] 2023-06-15 04:03
Thank you @a-maurice , I'll try this later today.

**Comment by lagoonbbbo** [comment] 2023-06-15 07:22
Ok, it worked !
Thank you very much.

**Comment by tejad** [comment] 2023-06-22 03:28
I was also having the same issue

> Hi @lagoonbbbo
> 
> Thanks for the bug report. The problem is that the symbols are being stripped by minification. We will try to get this fixed in the next release, but in the meantime, a pretty simple workaround is available.
> 
> In your `Assets/Plugins/Android/proguard-user.txt` file, you can add:
> 
> ```
> -keep,includedescriptorclasses public class com.google.firebase.remoteconfig.ConfigUpdateListenerRegistration { *; }
> ```

I was also having the same issue and this worked for me as well.

**Comment by a-maurice** [comment] 2023-06-28 00:44
Hey all,

The latest release, 11.2.0, includes this fix.  Thanks again for bringing this to our attention.

**Closed by a-maurice** 2023-06-28 00:44 UTC
Labels: api: remoteconfig, type: bug
