### ISSUE TITLE
[Bug] Uninstall button shown in google play store after user installs app from firebase dynamic link

### ISSUE THREAD

**Issue by thesanketkale** [firebase/firebase-unity-sdk#627] opened 2023-02-11 07:40 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: **2021.1.28f1**
  * Firebase Unity SDK version: **9.6.0**
  * Source you installed the SDK: **Unity Package Manager**
  * Problematic Firebase Component: **Dynamic Links**
  * Other Firebase Components in use: **Analytics & Messaging**
  * Additional SDKs you are using: **Login with Google**
  * Platform you are using the Unity editor on: **Windows**
  * Platform you are targeting: **Android and iOS**
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Pre-built SDK

### [REQUIRED] Please describe the issue here:
We have been using Firebase Dynamic Links in our project which since 2019 and it used to work as expected. But since updating to 9.6.0, our users have reported this issue to us saying upon installing the app from a dynamic or deep link, the Google Play Store only shows uninstall button on the app page. There is no way to open the app after installing the app, which results in breaking the whole flow for the user.
I have checked the configurations in the firebase console and also the Android Manifest in the plugins folder and everything looks ok, but still, this issue persists.

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:
1) Click on this link from a mobile device: https://link.vuexr.com/sl/vxrgBbwsXCsYM8nEA
2) It will open the app in Google Play Store
3) Install the app
4) After installing, you will only see uninstall button and no option to open the app to go to the content in the app

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? **Not checked**
What's the issue repro rate? (eg 100%, 1/5 etc) **100%**

**Comment by paulinon** [comment] 2023-02-13 15:45
Hi @thesanketkale,

I was able to replicate the issue with the steps you provided, but it seems that the cause of your issue may lie in the backend. If updating the SDK to the [latest version](https://firebase.google.com/support/release-notes/unity#version_1040_-_january_26_2023) doesn't make any difference, then It would be best to reach out to our [Firebase Support](https://firebase.google.com/support) since they have visibility with regards to backend issues. You may include your project details there so that they'll be able to assist you better. That said, I'll close this issue for now.

**Closed by paulinon** 2023-02-13 15:45 UTC
Labels: api: dynamiclinks, type: question
