### ISSUE TITLE
[Bug] Could not load image Assets\Firebase\Plugins\x86_64\FirebaseCppMessaging.dll due to Invalid Section Aligmnent 1000

### ISSUE THREAD

**Issue by KimYeonmu** [firebase/firebase-unity-sdk#479] opened 2022-10-05 03:07 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.14f1
  * Firebase Unity SDK version: 9.6.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: FirebaseMessaging (Auth, Database, etc.)
  * Other Firebase Components in use:  (Auth, Database, etc.)
  * Additional SDKs you are using:  (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Window 10 (Mac, Windows, or Linux)
  * Platform you are targeting: Android, iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: Mono (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

1. Install FirebaseMessgin.unitypackage
2. Print error code
3. 
![image](https://user-images.githubusercontent.com/38003448/193972337-b812b1bc-6938-4e4f-b56e-f9e280e8f918.png)

Could not load image D:\kym\Unity\MagicalInk\Assets\Firebase\Plugins\x86_64\FirebaseCppApp-9_6_0.dll due to Invalid Section Aligmnent 1000
Run the peverify utility against this for more information.

Could not load image D:\kym\Unity\MagicalInk\Assets\Firebase\Plugins\x86_64\FirebaseCppMessaging.dll due to Invalid Section Aligmnent 1000
Run the peverify utility against this for more information.

#### Steps to reproduce:

100%

#### Relevant Code:

No code is required.

**Comment by paulinon** [comment] 2022-10-05 11:37
Hi @KimYeonmu,

Thanks for bringing this to our attention. The error message seems rather unusual. I'd like you to answer these questions so that we can identify what's causing this behavior: 

1. Can this be reproduced by simply importing the Firebase SDK in an empty Unity project? If not, please provide more context on how this behavior could be replicated.
2. Does importing any other Firebase product produce the same result?
3. Could you try if updating your Unity editor version makes any difference?

**Comment by paulinon** [comment] 2022-10-06 09:20
Hi @KimYeonmu,

Could you provide the complete steps in replicating this behavior? A [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation would also be appreciated as this can be used as a baseline for troubleshooting. Also, are you using any other SDKs or plugins in your project? According to this [thread](https://forum.unity.com/threads/could-not-load-image-due-to-invalid-section-aligmnent-1000.1150829/), the error message may be caused by the [Dissonance plugin](https://placeholder-software.co.uk/dissonance/docs/index.html).

**Comment by KimYeonmu** [comment] 2022-10-13 01:20
Sorry I can't find reproducible example

This is the package I use.

Spine, DOTween, SmartLighting2D, UniRX, AntiCheatToolkit, LoopScrollRect

  "scopedRegistries": [
    {
      "name": "NPM",
      "url": "https://registry.npmjs.org",
      "scopes": [
        "com.fluid"
      ]
    }
  ],
  "dependencies": {
    "com.coffee.softmask-for-ugui": "https://github.com/mob-sakai/SoftMaskForUGUI.git",
    "com.fluid.behavior-tree": "2.2.0",
    "com.unity.2d.animation": "5.2.0",
    "com.unity.2d.pixel-perfect": "4.0.1",
    "com.unity.2d.psdimporter": "4.3.0",
    "com.unity.2d.sprite": "1.0.0",
    "com.unity.2d.spriteshape": "5.3.0",
    "com.unity.2d.tilemap": "1.0.0",
    "com.unity.2d.tilemap.extras": "1.5.0-preview",
    "com.unity.addressables": "1.19.17",
    "com.unity.cinemachine": "2.6.5",
    "com.unity.collab-proxy": "1.17.2",
    "com.unity.device-simulator": "3.0.1-preview",
    "com.unity.ide.rider": "3.0.15",
    "com.unity.ide.visualstudio": "2.0.16",
    "com.unity.ide.vscode": "1.2.5",
    "com.unity.memoryprofiler": "0.4.2-preview.1",
    "com.unity.mobile.android-logcat": "1.3.2",
    "com.unity.nuget.newtonsoft-json": "3.0.2",
    "com.unity.postprocessing": "2.3.0",
    "com.unity.project-auditor": "https://github.com/Unity-Technologies/ProjectAuditor.git",
    "com.unity.quicksearch": "2.0.2",
    "com.unity.test-framework": "1.1.31",
    "com.unity.textmeshpro": "3.0.6",
    "com.unity.timeline": "1.4.8",
    "com.unity.ugui": "1.0.0",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"


And I tried updating the editor to 2020.3.40f1, but the same problem occurred.

**Comment by paulinon** [comment] 2022-10-13 10:37
Thanks for the update, @KimYeonmu. It seems like this behavior is caused by the interaction between Firebase and another SDK in your implementation.

That being said, could you confirm if importing Firebase and one of your other SDKs produces the error message? It may seem like a lot, but I think we'll be making significant progress with this approach.

**Comment by KimYeonmu** [comment] 2022-10-18 01:56
I found a problem
Occurs when installing an older version of the AntiCheatToolkit.
AndroidNative.aar exists in the plug-in, which occurs here.

**Comment by KimYeonmu** [comment] 2022-10-18 02:02
https://assetstore.unity.com/packages/tools/utilities/anti-cheat-toolkit-2021-202695#content

I don't know if it's happening in the latest version, but the same file seems to exist in the latest version.

Plugins/CodeStage/AntiCheatToolkit/Runtime/Plugins/Android/AndroidNative.aar

**Comment by KimYeonmu** [comment] 2022-10-18 02:15
I found a problem
Occurs when installing an older version of the AntiCheatToolkit
I don't know if it's happening in the latest version

**Comment by paulinon** [comment] 2022-10-18 09:06
Thanks for the update, @KimYeonmu. In that case, you may get in touch with them and raise this concern via their [website](https://codestage.net/contacts). That said, I'll be closing this for now.

**Closed by paulinon** 2022-10-18 09:06 UTC
Labels: api: core, needs-attention, type: question
