### ISSUE TITLE
[Bug] Undefined symbol: _SWIG_csharp_string_size, _SWIG_csharp_string_str, _SWIG_csharp_string_to_c

### ISSUE THREAD

**Issue by gokhancnr** [firebase/firebase-unity-sdk#1139] opened 2024-11-05 19:18 UTC
### Description

I've upgraded my **Unity(6000.0.25f1)** Projects's **Firebase SDK to 11.4.0**

When I try to Archieve to distribute it it gives me error:

![image](https://github.com/user-attachments/assets/02ea4cfd-c548-4c85-b027-ab1d5b87857a)

When I searched for:

**- _SWIG_csharp_string_size**
**- _SWIG_csharp_string_str**
**- _SWIG_csharp_string_to_c**

they are all used by Firebase products:

![image](https://github.com/user-attachments/assets/f10354dc-b5bd-4c3a-bb9d-4853887a92a5)

What I've tried:

- Downgrade Xcode
- pod install
- update cocoapods
- Add GameKit.framework

### Firebase Unity SDK Version

12.4.0

### Unity editor version

6000.0.25f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Analytics, Crashlytics, Messaging, Remote Config

### Additional SDKs you are using

AdMob

### Targeted Platform(s)

Apple Platforms

### Unity editor platform

Mac

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### Relevant Log Output

```shell
Undefined symbols for architecture arm64:
  "_SWIG_csharp_string_size", referenced from:
      _SWIGStringWithLengthHelper_SWIG_csharp_string_size_m8F346145417F2C9491498D803A31784BD19013D7 in libGameAssembly.a[22](vu34smn0bqak.o)
      _SWIGStringWithLengthHelper_SWIG_c_to_csharp_string_mE1E23481DA0D5785F7A93B2E2198C097C57B3D5C in libGameAssembly.a[22](vu34smn0bqak.o)
      _SWIGStringWithLengthHelper_SWIG_csharp_string_size_m16FB33E0B820555284400210117E7A8A52B532FA in libGameAssembly.a[23](mz5zwj743dgj.o)
      _SWIGStringWithLengthHelper_SWIG_c_to_csharp_string_m84428208EED10043F30F6C512792615AE2FAC037 in libGameAssembly.a[23](mz5zwj743dgj.o)
      _SWIGStringWithLengthHelper_SWIG_csharp_string_size_m1948ACEBEE67E05211F90DE17590914433C663CE in libGameAssembly.a[25](q0ur51tkyt20.o)
      _SWIGStringWithLengthHelper_SWIG_c_to_csharp_string_mC21BFB1DCB3E5CD72C79A7899554A8182198C5CF in libGameAssembly.a[25](q0ur51tkyt20.o)
      _SWIGStringWithLengthHelper_SWIG_csharp_string_size_m424013BA371C1172D562D03620F1633DB2259C20 in libGameAssembly.a[26](xt9xt4swnlqe.o)
      ...
  "_SWIG_csharp_string_str", referenced from:
      _SWIGStringWithLengthHelper_SWIG_csharp_string_str_m2D07EC24FFFF0DDD94E1F45C362A788592713A3A in libGameAssembly.a[22](vu34smn0bqak.o)
      _SWIGStringWithLengthHelper_SWIG_c_to_csharp_string_mE1E23481DA0D5785F7A93B2E2198C097C57B3D5C in libGameAssembly.a[22](vu34smn0bqak.o)
      _SWIGStringWithLengthHelper_SWIG_csharp_string_str_m83F8D0FCAAA6F3D1AC73C859088E835E8D9184FF in libGameAssembly.a[23](mz5zwj743dgj.o)
      _SWIGStringWithLengthHelper_SWIG_c_to_csharp_string_m84428208EED10043F30F6C512792615AE2FAC037 in libGameAssembly.a[23](mz5zwj743dgj.o)
      _SWIGStringWithLengthHelper_SWIG_csharp_string_str_m6D6B1401557AB973D33F49254FCCB69A4C94065D in libGameAssembly.a[25](q0ur51tkyt20.o)
      _SWIGStringWithLengthHelper_SWIG_c_to_csharp_string_mC21BFB1DCB3E5CD72C79A7899554A8182198C5CF in libGameAssembly.a[25](q0ur51tkyt20.o)
      _SWIGStringWithLengthHelper_SWIG_csharp_string_str_mE8CC0F094D3082710D19C93A28A2C3CF8297B371 in libGameAssembly.a[26](xt9xt4swnlqe.o)
      ...
  "_SWIG_csharp_string_to_c", referenced from:
      _SWIGStringWithLengthHelper_SWIG_csharp_string_to_c0_mFE6E5675C210B8A012509DFC8D1733ED4BFF08B3 in libGameAssembly.a[22](vu34smn0bqak.o)
      _SWIGStringWithLengthHelper_SWIG_csharp_string_to_c_m8215BCAC3D160AF742FDBFAE9C3721158B1C1847 in libGameAssembly.a[22](vu34smn0bqak.o)
      _SWIGStringWithLengthHelper_SWIG_csharp_string_to_c0_m4748CBC22A07C4460FCE76182618154259A699AB in libGameAssembly.a[23](mz5zwj743dgj.o)
      _SWIGStringWithLengthHelper_SWIG_csharp_string_to_c_m987FC6537DCF628964F5623A836D12D2D153A61D in libGameAssembly.a[23](mz5zwj743dgj.o)
      _SWIGStringWithLengthHelper_SWIG_csharp_string_to_c0_mBFE7B39ECD66FBAC7F413F646B7537DF0736DBB7 in libGameAssembly.a[25](q0ur51tkyt20.o)
      _SWIGStringWithLengthHelper_SWIG_csharp_string_to_c_m04B714FEF399DC258EA140985995ED2B51EB5550 in libGameAssembly.a[25](q0ur51tkyt20.o)
      _SWIGStringWithLengthHelper_SWIG_csharp_string_to_c0_m0C29778A973671B9CA23102557968D5372D9B948 in libGameAssembly.a[26](xt9xt4swnlqe.o)
      ...
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by gokhancnr** [comment] 2024-11-06 14:25
Anybody?

**Comment by farazk86** [comment] 2024-11-10 13:36
Having the same issue with Unity 2022.3.52f1 and firebase 12.4.0

**Comment by JeongDongKyun** [comment] 2024-11-11 13:13
I can fixed of firebase version 12.0.0
Link: https://github.com/firebase/firebase-unity-sdk/releases?page=1

**Comment by JeongDongKyun** [comment] 2024-11-11 13:14
> I can fixed bug of firebase version 12.0.0 Link: https://github.com/firebase/firebase-unity-sdk/releases?page=1

**Comment by JeongDongKyun** [comment] 2024-11-11 14:50
You can try version 12.0.0

**Comment by argzdev** [comment] 2024-11-11 15:11
Hey folks, thanks for bringing this up to our attention. While we investigate this further, could you help me with the steps to reproduce this behavior?

What I did was the following, however I didn't encounter any issues:
1. Create a new project in Unity
2. Use `Assets > Import Package > Custom Package...`
3. Add version `12.4.0` of Firebase Analytics, Crashlytics, Messaging, RemoteConfig
4. Build project with iOS platform
5. Open in Xcode then select `Product > Archive`

Am I missing anything? Does this issue only happen during archiving or does it also happen when building? I'm also testing with Unity `6000.0.23f1` if that makes any difference.

**Comment by R1NoB** [comment] 2024-11-12 06:55
@argzdev I am using Unity 2022.3.26f1 version and I believe others are also using same Unity 2022.3.x version

**Comment by ajaybirla-fabzen** [comment] 2024-11-12 07:09
I'm also getting the same erros while building.

```
Undefined symbol: _SWIG_csharp_string_size
Undefined symbol: _SWIG_csharp_string_str
Undefined symbol: _SWIG_csharp_string_to_c
```

Unity: 2021.3.17f1
Xcode: 16.1
Firebase SDK: 12.4.0

**Comment by gokhancnr** [comment] 2024-11-12 09:03
Same for Unity(6000.0.26f1) unfortunately.

**Comment by ilterbilguven** [comment] 2024-11-12 11:38
Having same errors with Unity 6000.0.27f1 and Xcode 16.1.
Currently latest working version is 12.3.0

**Comment by a-maurice** [comment] 2024-11-13 01:31
Hi all,

While we haven't been able to reproduce the error ourselves, using disassembly tools I have spotted some additional symbols that are present in the C# libraries about SWIGStringWithLengthHelper, which seems to be the root cause of the issue.  While I try to determine a proper fix for this, unfortunately the best idea I have is to use 12.3.0.

Sorry for the inconvenience.

**Comment by hanilozmen** [comment] 2024-11-13 07:15
same problem with Xcode 16.1. v12.3.0 works with Xcode 16.1

**Comment by R1NoB** [comment] 2024-11-13 09:19
@hanilozmen where can we download 12.3.0 SDK? Can you paste the link here?

**Comment by R1NoB** [comment] 2024-11-13 10:28
@argzdev thank you for the link

**Comment by hanilozmen** [comment] 2024-11-13 11:08
> @hanilozmen where can we download 12.3.0 SDK? Can you paste the link here?

If you click Assets>Source Code links, it will start downloading specified Firebase version as a single bundle. 
https://github.com/firebase/firebase-unity-sdk/releases

**Comment by a-maurice** [comment] 2024-11-15 00:37
Alright, this should be resolved with the latest release https://github.com/firebase/firebase-unity-sdk/releases/tag/v12.4.1

I wasn't able to reproduce this error myself, but I confirmed with disassembly tools that the SWIGStringWithLengthHelper logic has been removed from the libraries, so hopefully it'll all be good to go.

Thanks for bringing this to our attention.

**Closed by a-maurice** 2024-11-15 00:37 UTC
Labels: api: core, needs-attention

**Comment by gokhancnr** [comment] 2024-11-15 06:53
And thanks for your interest.

As soon as I've seen regarding release I've tried to rebuild again.. and good news it's working.

Thanks again..
