### ISSUE TITLE
[Bug] Firebase crashes Unity everytime I press play

### ISSUE THREAD

**Issue by chriswalz** [firebase/firebase-unity-sdk#825] opened 2023-08-09 18:20 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.28
  * Firebase Unity SDK version: 11.3
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Firebase.Functions
  * Other Firebase Components in use: Firebase.App, Firebase.Analytics, Firebase.Firestore
  * Additional SDKs you are using: Oculus SDK
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the https://firebase.google.com/download/unity

### [REQUIRED] Please describe the issue here:

Unity Editor crashes everytime due to Firebase Unity SDK 

#### Steps to reproduce:

Unknown what's causing aside from a corrupted file and calling `db.collection`

#### Relevant Code:

Stacktrack from Editor.log 

```
ERROR: FIRESTORE INTERNAL ASSERTION FAILED: D:\a\firebase-unity-sdk\firebase-unity-sdk\windows_unity\bin\external\src\firestore\Firestore\core\src\local\leveldb_transaction.cc(78) void __cdecl firebase::firestore::local::LevelDbTransaction::Iterator::Seek(const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &): leveldb iterator reported an error: Corruption: block checksum mismatch (expected db_iter_->status().ok())
```

**Comment by dconeybe** [comment] 2023-08-09 19:26
It looks like Firestore's persistent database has gotten corrupted ("Corruption: block checksum mismatch"). You can likely recover by manually deleting the directory containing the persistent database.

To find the directory, enable Firestore's debug logging by setting `FirebaseFirestore.LogLevel = LogLevel.Debug` and reproducing the crash.

In the debug logs you should see a line that reads something like this:

```
Using c:\users\blah\...\somedirectory for LevelDB storage
```

See https://github.com/firebase/firebase-ios-sdk/blob/df562647810954fab9c957c0a88e7dd43edfc94e/Firestore/core/src/local/leveldb_opener.cc#L74

Delete that directory and try again.

**Comment by dconeybe** [comment] 2023-08-09 19:37
Also, if you're able, could you zip up the contents of that directory before you delete it and attach it to this bug report somehow? It would be interesting to take a look at it and see if we can understand why it is corrupted. If you cannot, or you're concerned about leaking information, that's totally fine too.

**Comment by chriswalz** [comment] 2023-08-09 20:35
Hi @dconeybe thank you so much this worked! I wasted so much time on looking into this but I'm glad it worked. 

I think what caused this particular problem is my power went out while doing some testing and it probably corrupting this local db (I wasn't aware that was even a thing let alone where it would be stored) 

I saved a clone of the folder but I am a bit worried about sharing it especially through a public place like github

**Comment by dconeybe** [comment] 2023-08-09 20:54
Ok I'm glad that worked for you. That's understandable that you don't want to share your database. If you do, however, have a few minutes, could you try opening it with a leveldb command-line utility to see if you get the same error message?
 https://www.google.com/search?q=leveldb+command+line

I'm going to close this issue since it's resolved. All the best!

**Closed** 2023-08-09 20:54 UTC
Labels: api: firestore, needs-attention, type: question
