### ISSUE TITLE
[Bug] DllNotFoundException: FirebaseCppApp-9_3_0 on Mojave OS Mac

### ISSUE THREAD

**Issue by gtoto007** [firebase/firebase-unity-sdk#437] opened 2022-08-05 13:29 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version:  2020.3.8f1
  * Firebase Unity SDK version: 9.3
  * Source you installed the SDK: .unitpackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: FirebaseApp (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on:  Mojave Mac (Mac, Windows, or Linux)
  * Platform you are targeting: Ios,Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

I upgraded the version of firebase from 7.* to 9.3. Some developers on our team use Mojave Mac OS and if they open Unity Editor they have the error _**DllNotFoundException: FirebaseCppApp-9_3_0 on Mojave Mac**_.

This error disappears if I force them to upgrade the OS, but it can be a problem because some have an old machine.

#### Steps to reproduce:

1. Install Mojave Mac OS
2. Create a new project Unity  with Firebase 9.3
3. The error _DllNotFoundException: FirebaseCppApp-9_3_0_  should be displayed. 
```

DllNotFoundException: FirebaseCppApp-9_3_0
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:3842)
Rethrow as TypeInitializationException: The type initializer for ‘SWIGExceptionHelper’ threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:3862)
Rethrow as TypeInitializationException: The type initializer for ‘Firebase.AppUtilPINVOKE’ threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4569)
Firebase.LogUtil..ctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:81)
Firebase.LogUtil..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:37)
Rethrow as TypeInitializationException: The type initializer for ‘Firebase.LogUtil’ threw an exception.
Firebase.FirebaseApp..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:1852)
Rethrow as TypeInitializationException: The type initializer for ‘Firebase.FirebaseApp’ threw an exception.
FirebaseService+<InitializeFirebase>d__10.MoveNext () (at Assets/AppData/Script/FirebaseService.cs:57)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
FirebaseService:Initialize(Action) (at Assets/AppData/Script/FirebaseService.cs:51)
SplashScreen_ViewManager:Start() (at Assets/AppData/Script/ViewManager/SplashScreen_ViewManager.cs:70)
```

**Comment by paulinon** [comment] 2022-08-05 15:14
Thanks for reporting this, @gtoto007. Are your developers facing an alert saying that Firebase cannot be verified when playing the scene? If so, I'd like you to have them try going to their Mac’s System Preferences > Security & Privacy then Click Allow Anyway corresponding to Firebase. 

Let me know if this solution made a difference.

**Comment by gtoto007** [comment] 2022-08-05 15:22
the request  _"Anyway corresponding to Firebase"_ isn't never showed  on Security&Privacy on Mojave Os.

**Comment by paulinon** [comment] 2022-08-11 16:29
Hi @gtoto007,

I've discussed this with the team, and we recommend that the software update is the way to go. Given that there's nothing in particular within the SDK that would cause the error message to appear, it's likely that this is caused by Apple's side.

That being said, I'll be closing this for now. Let me know if an issue arises.

**Closed by paulinon** 2022-08-11 16:29 UTC
Labels: api: core, needs-attention, type: question
