### ISSUE TITLE
[Bug] Can't use two windows desktop instances of game with different auth signin

### ISSUE THREAD

**Issue by Awais6** [firebase/firebase-unity-sdk#653] opened 2023-03-11 12:36 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.44f1
  * Firebase Unity SDK version: 10.4.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: _____ Auth
  * Other Firebase Components in use: _____ Firestore, Crashylytics
  * Additional SDKs you are using: _____ Facebook, AdMob, Photon
  * Platform you are using the Unity editor on: _____ Windows
  * Platform you are targeting: _____ desktop
  * Scripting Runtime: _____ (Mono)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

Can't use two windows desktop instances of game with different auth signin

#### Steps to reproduce:

Steps:
1) just add firebase auth into the fresh project and put ui button/scripts for test signin
2) build a universal windows desktop build with mono
3) run first instance
4) signin to any account
5) run second instance

the second instance will already be signed in with the same account as the first instance was on

I can't check the multiplayer games on the desktop build due to this bug

What's the issue repro rate? 100%

**Comment by Awais6** [comment] 2023-03-13 19:11
Any temporary workaround to test two instance of same game on windows?

**Comment by jonsimantov** [comment] 2023-03-13 20:39
Hi,

This is by design - the same app will persist its Auth signin between runs.

For debugging/testing, wou could add a call to auth.SignOut() at the start of your app - that will ensure that the persistent login is cleared at each instance.

**Comment by Awais6** [comment] 2023-03-14 11:30
> Hi,
> 
> This is by design - the same app will persist its Auth signin between runs.
> 
> For debugging/testing, wou could add a call to auth.SignOut() at the start of your app - that will ensure that the persistent login is cleared at each instance.

I understand, how this is working, Please understand the question, I want to run two instances of my game (desktop app) at the same time, so they can make a (Multiplayer) match together. When I run the game twice at the same time and just sign in any one of them, the other instance automatically signed as per the other instance. due to this behavior, both instances represent the same account.

I think this is because firebase auth persists the login data at the same location on the windows desktop, It should differ the persistent location by instance like instance path, instance number, etc.

**Comment by jonsimantov** [comment] 2023-03-14 18:30
The reason this is "by design" is that the saved user information is kept in Windows's secure credential storage (or the user's keychain on MacOS), it's not saved in the directory of the application executable. There's not an easy way to differentiate two instances of the same executable to store credentials in different places; it uses things like application bundle ID and Firebase App instance name to generate a key for persisting the credentials.

The stored credentials are only loaded on initialization of Firebase Auth, so if you sign out right after initializing Auth, it will clear out the saved credentials so you can log in as a different user.

**Comment by Awais6** [comment] 2023-03-14 19:10
Thank you so much for your quick response, I will try by signout at startup and update the issue accordingly.

**Comment by StephenHodgson** [comment] 2023-03-17 19:32
When we add credentials into the credentials store, is there a way to specifically identify each app instance? Shouldn't firebase have a unique instance ID for each application, even if it's on the same machine?

**Comment by jonsimantov** [comment] 2023-03-20 19:53
The application is identified by the bundle ID (as listed in the google-services.json file or equivalent). However, two instances of the same application running will, of course, have the same bundle ID.

**Comment by paulinon** [comment] 2023-04-19 17:48
Hi folks,

I see that a workaround has been provided for this issue. That said, I'll be closing this for now. Let me know if an issue arises with this solution.

**Closed by paulinon** 2023-04-19 17:48 UTC
Labels: api: auth, type: question
