### ISSUE TITLE
[Bug] Unity application crashes after updating Firebase SDK to 11.3.0

### ISSUE THREAD

**Issue by devolzhas** [firebase/firebase-unity-sdk#816] opened 2023-08-01 06:42 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.47f1
  * Firebase Unity SDK version: 11.3.0
  * Source you installed the SDK: FirebaseAuth_11.3.0.unitypackage
  * Problematic Firebase Component: One of the following Firebase Components in use
  * Other Firebase Components in use: Auth, Functions, Messaging, Firestore, RemoteConfig
  * Additional SDKs you are using:
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: website

### [REQUIRED] Please describe the issue here:

After updating Firebase SDK of our Unity application multiple crashes appeared. Update was from Firebase SDK 10.7.0 to 11.3.0

[1]
[libFirebaseCppApp-11_3_0.so] firebase::auth::User::is_email_verified() const
SIGSEGV

<img width="785" alt="image" src="https://github.com/firebase/firebase-unity-sdk/assets/84438635/23238a07-6a41-415a-beeb-a3cd9d240b97">

**Crash Log**:
Stack Trace:
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 2526 >>> [app-name] <<<

backtrace:
  #00  pc 0x0000000000271bae  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libFirebaseCppApp-11_3_0.so (firebase::auth::User::is_email_verified() const+30)
  #01  pc 0x00000000002007af  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libFirebaseCppApp-11_3_0.so (Firebase_Auth_CSharp_FirebaseUser_IsEmailVerified_get+6)
  #02  pc 0x000000000506c8a4  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libil2cpp.so
  #03  pc 0x0000000005070618  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libil2cpp.so
  #04  pc 0x0000000001214548  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libil2cpp.so
  #05  pc 0x000000000291e820  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libil2cpp.so
  #06  pc 0x000000000074d068  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libil2cpp.so
  #07  pc 0x0000000000be4220  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libil2cpp.so
  #08  pc 0x000000000026eb3d  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libunity.so (scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool))
  #09  pc 0x00000000002718a1  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libunity.so (ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool))
  #10  pc 0x0000000000280057  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libunity.so (Coroutine::InvokeMoveNext(ScriptingExceptionPtr*))
  #11  pc 0x000000000027fd9b  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libunity.so (Coroutine::Run(bool*))
  #12  pc 0x000000000017b7af  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libunity.so (DelayedCallManager::Update(int))
  #13  pc 0x00000000001e7c31  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libunity.so (ExecutePlayerLoop(NativePlayerLoopSystem*))
  #14  pc 0x00000000001e7c4d  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libunity.so (ExecutePlayerLoop(NativePlayerLoopSystem*))
  #15  pc 0x00000000001e7de9  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libunity.so (PlayerLoop())
  #16  pc 0x00000000002c6a79  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libunity.so (UnityPlayerLoop())
  #17  pc 0x00000000002d67dd  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/lib/arm/libunity.so (nativeRender(_JNIEnv*, _jobject*))
  #18  pc 0x0000000000090ddb  /data/app/[app-name]-OY3mhaQjBbjhg7E-0G6Bfw==/oat/arm/base.odex

[2]
[libFirebaseCppApp-11_3_0.so] Firebase_Auth_CSharp_FirebaseUser_UserId_get
SIGSEGV

<img width="350" alt="image" src="https://github.com/firebase/firebase-unity-sdk/assets/84438635/1077f8d7-91ca-4564-ad72-f9f47b7d37e1">

**Crash Log**:
Stack Trace:
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 824 >>> [app-name] <<<

backtrace:
  #00  pc 0x0000000000201c5c  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libFirebaseCppApp-11_3_0.so (Firebase_Auth_CSharp_FirebaseUser_UserId_get+36)
  #01  pc 0x0000000004f7a3fc  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libil2cpp.so
  #02  pc 0x0000000004f7d738  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libil2cpp.so
  #03  pc 0x0000000004ced588  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libil2cpp.so
  #04  pc 0x00000000038a5958  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libil2cpp.so
  #05  pc 0x0000000002e61b40  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libil2cpp.so
  #06  pc 0x000000000271edb0  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libil2cpp.so
  #07  pc 0x0000000004cf1318  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libil2cpp.so
  #08  pc 0x00000000038a5958  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libil2cpp.so
  #09  pc 0x0000000003f65518  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libil2cpp.so
  #10  pc 0x0000000004c628fc  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libil2cpp.so
  #11  pc 0x0000000004c62878  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libil2cpp.so
  #12  pc 0x00000000011cfd60  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libil2cpp.so
  #13  pc 0x00000000015fbe40  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libil2cpp.so
  #14  pc 0x00000000003addcc  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libunity.so (scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool))
  #15  pc 0x00000000003b1d10  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libunity.so (ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool))
  #16  pc 0x00000000009ae840  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libunity.so (Scripting::UnityEngine::UnitySynchronizationContextProxy::ExecuteTasks(ScriptingExceptionPtr*))
  #17  pc 0x00000000002f5edc  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libunity.so (ExecutePlayerLoop(NativePlayerLoopSystem*))
  #18  pc 0x00000000002f5f10  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libunity.so (ExecutePlayerLoop(NativePlayerLoopSystem*))
  #19  pc 0x00000000002f6154  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libunity.so (PlayerLoop())
  #20  pc 0x000000000042c7b0  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libunity.so (UnityPlayerLoop())
  #21  pc 0x000000000044289c  /data/app/~~AW68MwoiuG1i4V3Eoozc2w==/[app-name]-qZtvYph-jWIBEqm7rN7uvQ==/lib/arm64/libunity.so (nativeRender(_JNIEnv*, _jobject*))
  #22  pc 0x0000000000222244  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148)
  #23  pc 0x0000000000212520  /apex/com.android.art/lib64/libart.so (nterp_helper+4016)
  #24  pc 0x00000000020007b4  /memfd:jit-cache

[3]
[libFirebaseCppApp-11_3_0.so] firebase::App::GetJNIEnv() const
SIGSEGV

<img width="350" alt="image" src="https://github.com/firebase/firebase-unity-sdk/assets/84438635/84bb0bf1-890e-438a-a3db-cca0ab9835b9">

**Crash Log**:
Stack Trace:
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 18458 >>> [app-name] <<<

backtrace:
  #00  pc 0x00000000001a2060  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libFirebaseCppApp-11_3_0.so (firebase::App::GetJNIEnv() const)
  #01  pc 0x00000000002c2a20  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libFirebaseCppApp-11_3_0.so (firebase::auth::User::is_email_verified() const+36)
  #02  pc 0x0000000000201914  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libFirebaseCppApp-11_3_0.so (Firebase_Auth_CSharp_FirebaseUser_IsEmailVerified_get+12)
  #03  pc 0x0000000004f7a374  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libil2cpp.so
  #04  pc 0x0000000004f7d62c  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libil2cpp.so
  #05  pc 0x0000000001b6acd4  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libil2cpp.so
  #06  pc 0x0000000002ea8cc4  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libil2cpp.so
  #07  pc 0x00000000011a8e3c  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libil2cpp.so
  #08  pc 0x00000000015fbe40  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libil2cpp.so
  #09  pc 0x00000000003addcc  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libunity.so (scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool))
  #10  pc 0x00000000003b1d10  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libunity.so (ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool))
  #11  pc 0x00000000003c68d4  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libunity.so (Coroutine::InvokeMoveNext(ScriptingExceptionPtr*))
  #12  pc 0x00000000003c64b4  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libunity.so (Coroutine::Run(bool*))
  #13  pc 0x0000000000262fb4  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libunity.so (DelayedCallManager::Update(int))
  #14  pc 0x00000000002f5edc  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libunity.so (ExecutePlayerLoop(NativePlayerLoopSystem*))
  #15  pc 0x00000000002f5f10  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libunity.so (ExecutePlayerLoop(NativePlayerLoopSystem*))
  #16  pc 0x00000000002f6154  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libunity.so (PlayerLoop())
  #17  pc 0x000000000042c7b0  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libunity.so (UnityPlayerLoop())
  #18  pc 0x000000000044289c  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/lib/arm64/libunity.so (nativeRender(_JNIEnv*, _jobject*))
  #19  pc 0x00000000000655ec  /data/app/[app-name]-IG71AojIwq8SqUJx9iX4_Q==/oat/arm64/base.odex

#### Steps to reproduce:

It's unclear what the real trigger is, it happens on Android devices

**Comment by paulinon** [comment] 2023-08-01 15:31
Hi @devolzhas,

Thanks for reporting this. Based on the stack traces you provided, it appears that Firebase is referenced in your crashes with some pointing to Auth. That said, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation so we can identify what's causing this behavior? You may upload this to a GitHub repository with all personally identifiable information scrubbed and add me as a collaborator. You can also try out our [quickstart](https://github.com/firebase/quickstart-unity/tree/master/auth/testapp) project to see if the issue persists in another project.

**Comment by cometa93** [comment] 2023-08-08 20:48
@paulinon, it's the SAME BUG we reported, and you still don't do shit about it; it's since 11.1... AUTH is f*** right now... and your bot is closing all tickets. 

This way you won't fix shit.

**Comment by AlmostMatt** [comment] 2023-08-14 22:12
I notice that the stack trace for this crash mentions firebase::auth::User::is_email_verified(), which is a method on the User object. There is a decent probability that this is a duplicate of #819, where calling a method on a C# User object can cause a crash if corresponding internal C++ memory has been cleaned up.

@devolzhas 
If this is the same issue as 819, then as a workaround you can try using the CurrentUser variable to get a fresh User object instead of calling methods on an old User object. If it is the same underlying issue, then the fix that is in-progress for issue 819 will resolve this as well. If however the workaround does not help, then it is a separate issue and if you are able to provide any additional information about code that can be used to reproduce this would help speed out debugging.

**Comment by a-maurice** [comment] 2023-08-17 20:23
Hi @devolzhas 

The latest release 11.4.0, https://github.com/firebase/firebase-unity-sdk/releases/tag/v11.4.0, reworked the FirebaseUser class a bit to avoid the problems that were likely causing the crash.  Hard to know for sure, since the repro steps were unclear, but hopefully it will be fixed.

I'll close this for now, but if you are still seeing it after upgrading, please let us know.

**Closed by a-maurice** 2023-08-17 20:23 UTC
Labels: api: auth, needs-info, type: question
