### ISSUE TITLE
[Bug] Unity 6, AdMob & Firebase SDKs -- duplicated attribute property#android.adservices.AD_SERVICES_CONFIG

### ISSUE THREAD

**Issue by manelizzard** [firebase/firebase-unity-sdk#1137] opened 2024-11-05 10:52 UTC
### Description

Impossible to build Android on Unity 6 with AdMob & Firebase SDKs. The resulting error is:

```
Attribute property#android.adservices.AD_SERVICES_CONFIG@resource value=(@xml/gma_ad_services_config) from [com.google.android.gms:play-services-ads-lite:23.2.0] AndroidManifest.xml:92:13-59
	is also present at [com.google.android.gms:play-services-measurement-api:22.0.2] AndroidManifest.xml:32:13-58 value=(@xml/ga_ad_services_config).
	Suggestion: add 'tools:replace="android:resource"' to <property> element at AndroidManifest.xml to override.
```

The involved libraries are:
- `firebase-analytics`, depending on `play-services-measurement-api`
- `google-adapter`, depending on `play-services-ads-lite`

While there is a workaround by using `tools:replace` on main `AndroidManifest.xml`, may worth exploring a real compatibility within those two SDKs

```
    <property android:name="android.adservices.AD_SERVICES_CONFIG" android:resource="@xml/gma_ad_services_config" tools:replace="android:resource" />
```

Some references: [here](https://stackoverflow.com/questions/78085458/manifest-merger-failed-with-agp-8-3-0), [here](https://issuetracker.google.com/issues/327696048?pli=1) and [here](https://stackoverflow.com/questions/43140059/add-toolsreplace-androidvalue-to-meta-data-element-at-androidmanifest)

### Reproducing the issue

- Create a new Unity project with any Unity 6 version
- Import latest Firebase Unity SDK (at least analytics package)
- Import Google AdMob ad network (in our case, done through AppLovin MAX adapter)
- Try to build: build fails with the mentioned error

### Firebase Unity SDK Version

12.4.0

### Unity editor version

6000

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Analytics

### Additional SDKs you are using

AdMob

### Targeted Platform(s)

Android

### Unity editor platform

Mac

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### Relevant Log Output

```shell
Attribute property#android.adservices.AD_SERVICES_CONFIG@resource value=(@xml/gma_ad_services_config) from [com.google.android.gms:play-services-ads-lite:23.2.0] AndroidManifest.xml:92:13-59
	is also present at [com.google.android.gms:play-services-measurement-api:22.0.2] AndroidManifest.xml:32:13-58 value=(@xml/ga_ad_services_config).
	Suggestion: add 'tools:replace="android:resource"' to <property> element at AndroidManifest.xml to override.
```

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by argzdev** [comment] 2024-11-05 14:42
Hey @manelizzard, thanks for reaching out. This is duplicate of #1127. So as discussed, the issue is due to the transitive dependency of Firebase and Admob. The stacktrace shows that these libraries are causing the conflict:
```
com.google.android.gms:play-services-measurement-api:22.1.2
com.google.android.gms:play-services-ads-lite:23.4.0
```

> Both of which are libraries from the Google Play Services. A discussion with the AGP team in the public bug link: https://issuetracker.google.com/issues/327696048 determines that these dependencies has to fix it on their side. Once those fixes are applied, it will then trickle down to our SDKs.

There's not much we can do on our SDK since it is only grabbing those dependencies. I'd recommend following up on the public bug link to get feedback. I'll go ahead and close this thread.

**Closed by argzdev** 2024-11-05 14:42 UTC
Labels: api: analytics

**Comment by manelizzard** [comment] 2024-11-05 15:33
Thank you, was not able to find the duplicated. Sorry for that
