### ISSUE TITLE
[Bug] Firebase AppCheck requires Android Min SDK version 24 but min SDK 23 is mentioned ChangeLogs of 12.4.0

### ISSUE THREAD

**Issue by smakarov** [firebase/firebase-unity-sdk#1144] opened 2024-11-09 19:15 UTC
### Description

Description
Firebase SDK requires Android Min SDK version 24 but not defined in changelog and it should work fine with minSDK 23 as mentioned in the changelogs of Firebase SDK 12.4.0. With and min sdk 23 AppCheck it fails, with min sdk builds fine.
Reproducing the issue
Install Firebase AppCheck SDK 12.4.0 and try to build by defining 23 as minSDK in Unity Project Settings.

Firebase Unity SDK Version
12.4.0

Unity editor version
2022.3.52f1

Installation Method
.unitypackage

Problematic Firebase Component(s)
AppCheck

Other Firebase Component(s) in use
Analytics, Authentication, Crashlytics, Remote Config

Targeted Platform(s)
Android

Unity editor platform
Win 10

Scripting Runtime
IL2CPP

### Firebase Unity SDK Version

12.4.0

### Unity editor version

2022.3.52f

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

App Check

### Other Firebase Component(s) in use

Analytics, Crashlytics, Messaging, Remote Config

### Targeted Platform(s)

Android

### Unity editor platform

Windows

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### Relevant Log Output

```shell
Could not resolve all files for configuration ':launcher:releaseRuntimeClasspath'. See the Console for details.


* What went wrong:
Execution failed for task ':launcher:mergeExtDexRelease'.
> Could not resolve all files for configuration ':launcher:releaseRuntimeClasspath'.
   > Failed to transform play-services-measurement-api-22.1.2.aar (com.google.android.gms:play-services-measurement-api:22.1.2) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=false, dexing-min-sdk=23, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: C:\Users\Teq\.gradle\caches\transforms-3\fb03720faca274bb849b0038ff46085b\transformed\jetified-play-services-measurement-api-22.1.2-runtime.jar.
         > Error while dexing.


CommandInvokationFailure: Gradle build failed. 
C:\Program Files\2022.3.52f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK\bin\java.exe -classpath "C:\Program Files\2022.3.52f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-7.5.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"
```

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by argzdev** [comment] 2024-11-14 12:39
Hey @smakarov, thanks for reaching out. I was able to reproduce the same behavior. I'll notify our engineers and see what we can do here.

**Comment by a-maurice** [comment] 2024-11-20 22:33
The core of this issue is with the dex tool that is included with the gradle / Android tools that comes with the Unity editor now.  Unfortunately, it is hard to fix on our end, as a lot of the fixes depend on project configuration which are hard to generalize.

A couple of potential fixes for the issue:
1. Updating to minSdkVersion to 24+
2. Turning on Android minification, since proguard avoids this
3. Specify a different version of the dex tool, it should be something like adding this to the settingsTemplate.gradle file:
```
buildscript {
  repositories {
    mavenLocal()
    maven { url 'https://maven.google.com'  }
    mavenCentral()
  }
  dependencies {
    classpath 'com.android.tools:r8:8.3.37'
  }
}
```
4. Upgrade the gradle version you're using

I'll close this issue for now, since we don't have any plans to address this beyond these workarounds.

**Closed by a-maurice** 2024-11-20 22:33 UTC
Labels: type: bug, api: appcheck

**Comment by gokhancnr** [comment] 2024-12-07 14:37
Thank you. I know it took sometime to respond. It was my bad to give them a try one by one but when I totally apply it worked like a charm!
