### ISSUE TITLE
[Question]  Auth not working in Unity editor

### ISSUE THREAD

**Issue by zxt385189207** [firebase/firebase-unity-sdk#1098] opened 2024-08-30 12:23 UTC
### What is your question?

Unable to signin properly in the unity editor environment, but can sginin and upload and download files on my Android phone.

FirebaseException: An internal error has occurred.

I don't know where the setup caused this problem and I can't test the functionality in the unity editor.

Something like that https://github.com/firebase/firebase-cpp-sdk/issues/10  ,  I wrote a simple demo with no other SDK.

I need help, please.

```
Firebase.FirebaseApp.LogLevel = Firebase.LogLevel.Verbose;
```

```
Added app name=__FIRAPP_DEFAULT: options, api_key=..., app_id=....., database_url=, messaging_sender_id=....., storage_bucket=test-xxxx.appspot.com, project_id=test-xxxx (0x01788e20)
UnityEngine.Debug:Log (object)

Creating Auth ..... for App ....
UnityEngine.Debug:Log (object)

Cloud Storage gs://test-xxxxxx.appspot.com: Created __FIRAPP_DEFAULTgs://test-xxxxx.appspot.com
UnityEngine.Debug:Log (object)

LoadUserData: Credential com.xxxx.xxxx.test-xxxx.firebase.auth/__FIRAPP_DEFAULT[0] not found
UnityEngine.Debug:Log (object)

Failed to read user data for app (__FIRAPP_DEFAULT).  This could happen if the current user doesn't have access to the keystore, the keystore has been corrupted or the app intentionally deleted the stored data.
UnityEngine.Debug:Log (object)

DeleteUserData: Credential com.xxxx.xxxx.test-xxxx.firebase.auth/__FIRAPP_DEFAULT[0] not found
UnityEngine.Debug:Log (object)
```

### Firebase Unity SDK Version

11.6.0 and 12.2.0

### Unity editor version

2021.3.12f1

### Installation Method

Unity Package Manager

### Problematic Firebase Component(s)

Authentication

### Other Firebase Component(s) in use

Storage

### Targeted Platform(s)

Desktop

### Unity editor platform

Windows

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

**Comment by argzdev** [comment] 2024-08-30 14:01
Thanks for reaching out, @zxt385189207. There was also a similar issue filed before #1048 regarding Auth login. Did you recently change the [app bundle name](https://github.com/firebase/firebase-unity-sdk/issues/1048#issuecomment-2180176654)? This could have triggered the issue.

**Comment by zxt385189207** [comment] 2024-08-31 08:14
> Thanks for reaching out, @zxt385189207. There was also a similar issue filed before #1048 regarding Auth login. Did you recently change or restrict the [API access](https://github.com/firebase/firebase-unity-sdk/issues/1048#issuecomment-2180176654)? This could have triggered the issue.

I did not impose any restrictions, or is it possible that Firebase has default settings?

**Comment by zxt385189207** [comment] 2024-09-01 13:51
By the way, on another computer the same project printed USE_AUTH_EMULATOR not set.

**Comment by zxt385189207** [comment] 2024-09-01 14:07
```
        private void Start()
        {
            Firebase.FirebaseApp.LogLevel = Firebase.LogLevel.Verbose;
            FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task =>
            {
                FirebaseApp app = FirebaseApp.DefaultInstance;
                auth = FirebaseAuth.DefaultInstance;
            });
        }


// SignInAnonymouslyAsync Button onclick
           try
            {
                var result = await auth.SignInAnonymouslyAsync().AsUniTask();
                if (result.User != null && result.User.IsValid())
                {
                    ...
                }
                else
                {
                    ...
                }
            }
            catch (Exception e)
            {
                ....
            }



        private void OnDestroy()
        {
            if (auth != null)
            {
                auth.StateChanged   -= AuthStateChanged;
                auth.IdTokenChanged -= IdTokenChanged;
                auth                =  null;
            }
        }
```

![QQ_1725199175453](https://github.com/user-attachments/assets/5e1d3726-8699-4922-a1a7-44c81bee9e17)

With this code, turning off UNITYEDITOR can wait indefinitely. 
So What's the problem?

**Comment by argzdev** [comment] 2024-09-02 11:17
Sorry, I'm not sure what the issue is. I'm unable to reproduce the same behavior on my side. You mentioned that the issue is also reproducible on another computer, I wonder if the issue is the `google-services.json`. Could you try using a different Firebase project and see if the same behavior is encountered?

Also any chance you can share an [MCVE](https://meta.stackoverflow.com/questions/366988/what-does-mcve-mean)? Please remove any PII (personally identifiable information). This'll help us speed up the investigation. Thanks!

**Comment by argzdev** [comment] 2024-09-03 17:01
Thanks for the additional information, @zxt385189207. You're right, given that you're using the official Auth sample code, the MCVE will most likely work on our side as well. After further discussing this with our engineers, we came to the conclusion that the issue is due to the network restriction and not related to the `google-services.json`.

> In what situations does this error occur, and how can the client determine whether the issue is related to the network or the google-services.json ?

I thought it could be due to a specific Firebase Project API restriction, which is why I considered changing the `google-services.json` to another project which might cause a different behavior, but this doesn't seem to be the case. And now, it most certainly is due to a network restriction.

Unfortunately there's not much we can do here, since it looks like everything is working as intended on the SDK side. Network restrictions are out of our control. That said, I'll go ahead and close this thread. If you'd like to know more regarding these restrictions in relation to China, feel free to reach out to our [Firebase support](https://firebase.google.com/support) for more guidance.

**Closed by argzdev** 2024-09-03 17:01 UTC
Labels: api: auth, needs-attention

**Comment by zxt385189207** [comment] 2024-09-04 01:36
Can a proxy setting be added to network requests made by the Firebase SDK in Unity? @argzdev

**Comment by argzdev** [comment] 2024-09-04 09:10
Sorry, you'll likely need to reach out to our [Firebase support](https://firebase.google.com/support) for more guidance regarding network connections.
