### ISSUE TITLE
scripting_method_invoke - Crashlytics Report [Bug] 

### ISSUE THREAD

**Issue by tlovidiu92** [firebase/firebase-unity-sdk#810] opened 2023-07-25 10:43 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.25f
  * Firebase Unity SDK version: 11.2.0
  * Problematic Firebase Component: Auth, Realtime DB, Messaging, Crashlytics, Analytics

### [REQUIRED] Please describe the issue here:
Hello,

We keep getting this error on the crashlytics reports:
#### Relevant Code:

```
`null pointer dereference: SIGSEGV  0x0000000000000052
#00 pc 0x9299d8 libil2cpp.so (BuildId: b9de258eeafd0d9e3ef705d9b4f885e4bd0fe08c)
#01 pc 0x2fb9b0 libunity.so (scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool)) (BuildId: 7a12f09baa8a6034030e1d89c716b083429a5d4e)
#02 pc 0x701b3bd33a
#03 pc 0x20087c libart.so (BuildId: 4bf4747707ca903605931dd6b3d0480c)
#04 pc 0x209334 libart.so (BuildId: 4bf4747707ca903605931dd6b3d0480c)
#05 pc 0x701b3bd33a
#06 pc 0x70cd5b74
#07 pc 0x458000 libart.so (BuildId: 4bf4747707ca903605931dd6b3d0480c)
#08 pc 0x5caf34 libart.so (BuildId: 4bf4747707ca903605931dd6b3d0480c)
#09 pc 0x60308 libc.so (BuildId: cd953571180b7f5f8ae5570dad29595f)`
```

**Comment by paulinon** [comment] 2023-07-26 14:27
Hi @tlovidiu92,

[Version 11.3.0](https://firebase.google.com/support/release-notes/unity#version_1130_-_july_19_2023) of the SDK has been released. Could you try it out and see if the issue persists?

Also, the stack trace you provided doesn't seem to reference Firebase. Are there any additional SDKs in your implementation? It would be helpful if you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation along with the complete steps to reproduce the issue as this as a baseline for our troubleshooting. You may also share the specifications of the devices (i.e. OS version, model) that are facing this crash so we can narrow down what's causing this to happen.

**Comment by tlovidiu92** [comment] 2023-07-26 17:33
This is happening to 3% of our users. On Android. We cannot reproduce it. We only have the crashlytics report

**Comment by paulinon** [comment] 2023-07-27 09:51
Hi @tlovidiu92,

Are there any other SDKs in your implementation? We can't determine if Firebase is causing the crashes based on the provided stack trace alone. Also, it would be helpful if you try version 11.3.0 and collect the latest stack trace so that you'll have the latest fixes and updates related to Firebase.

**Comment by tlovidiu92** [comment] 2023-07-27 11:06
We are now trying an update of the firebase sdk to 11.3.0. We are also
using some advertising sdks and Photon. But the problem started when we
integrated the firebase authentication and real-time database. This issue
is not present on iOS.

**Comment by tlovidiu92** [comment] 2023-07-30 06:18
I got a longer crashlytics report, maybe this helps:

`null pointer dereference: SIGSEGV  0x0000000000000008
#00 pc 0xa6308296
#01 pc 0x2cfd1ff libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#02 pc 0x2c3b2ce libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#03 pc 0xad31a2 libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#04 pc 0x14e951e libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#05 pc 0xa0019a libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#06 pc 0xd0cc66 libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#07 pc 0xd0d6a6 libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#08 pc 0xafb772 libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#09 pc 0xafba82 libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#10 pc 0x2c2cee6 libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#11 pc 0xcc4be libc.so (BuildId: 0bf27f8fcefe3acc55b2dd5ca6e5b4aa)
#12 pc 0xafe742 libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#13 pc 0x3c03aa libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#14 pc 0x4cb79a libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#15 pc 0x3f338a libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#16 pc 0x4cb5f6 libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#17 pc 0x1ef509 libunity.so (scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool)) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#18 pc 0xe65a62 libunity.so (__ashldi3) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#19 pc 0x1f9aa3 libunity.so (ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool)) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#20 pc 0x20342b libunity.so (MonoBehaviour::CallUpdateMethod(int)) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#21 pc 0x2a3847 libunity.so (NavMeshManager::Update()) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#22 pc 0x87d36d libunity.so (Scripting::UnityEngine::SendMouseEventsProxy::DoSendMouseEvents(int, ScriptingExceptionPtr*)) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#23 pc 0x39fe79 libunity.so (PhysicsManager2D::InterpolateBodies()) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#24 pc 0x2fece1 vulkan.adreno.so (BuildId: 335dde09a52ce90acb724a26ba4d74f7)
#25 pc 0xe878c6 libunity.so (__ashldi3) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#26 pc 0x889149 libunity.so (VideoPlaybackMgr::DispatchMediaDecode()) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#27 pc 0x1de5c9 libunity.so (ManagedTempMemScope::ManagedTempMemScope(bool)) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#28 pc 0xe1eb1 libunity.so (void BaseBehaviourManager::CommonUpdate<BehaviourManager>()) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#29 pc 0x15d3cb libunity.so (ExecutePlayerLoop(NativePlayerLoopSystem*)) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#30 pc 0x47a17 libc++.so (BuildId: 236447ad56e9c71a5e6e61ab4a09d7ed)
#31 pc 0x267d01 libart.so (BuildId: b4ba4554d0e918127f6537060375c4bf)
#32 pc 0x211e25 libart.so (BuildId: b4ba4554d0e918127f6537060375c4bf)
#33 pc 0xe878c6 libunity.so (__ashldi3) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#34 pc 0x3f17ee libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#35 pc 0x4cb79a libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#36 pc 0xc1283e libunity.so (__gnu_ldivmod_helper) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#37 pc 0xe767e libart.so (BuildId: b4ba4554d0e918127f6537060375c4bf)
#38 pc 0xc5a989bc
#39 pc 0x4cb5f6 libil2cpp.so (BuildId: 47683010e37de3dd50e36a4ccc8d02a75ec6b1ff)
#40 pc 0xc5a989bc
#41 pc 0x1ef509 libunity.so (scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool)) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#42 pc 0x15d3ef libunity.so (ExecutePlayerLoop(NativePlayerLoopSystem*)) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#43 pc 0xe68b06 libunity.so (__ashldi3) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#44 pc 0x26b953 libunity.so (Scripting::UnityEngine::Rendering::OnDemandRenderingProxy::GetRenderFrameInterval(int*, ScriptingExceptionPtr*)) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#45 pc 0xe65a62 libunity.so (__ashldi3) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#46 pc 0x1f9aa3 libunity.so (ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool)) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#47 pc 0xe68b06 libunity.so (__ashldi3) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#48 pc 0x26b953 libunity.so (Scripting::UnityEngine::Rendering::OnDemandRenderingProxy::GetRenderFrameInterval(int*, ScriptingExceptionPtr*)) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#49 pc 0x2d891 libc.so (BuildId: 0bf27f8fcefe3acc55b2dd5ca6e5b4aa)
#50 pc 0x14960b libunity.so (SimulateInputEvents(int, bool*)) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#51 pc 0xe767e libart.so (BuildId: b4ba4554d0e918127f6537060375c4bf)
#52 pc 0xc5a989bc
#53 pc 0xc1283e libunity.so (__gnu_ldivmod_helper) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#54 pc 0xe5f5b3 libunity.so (__ashldi3) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#55 pc 0xe68b06 libunity.so (__ashldi3) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#56 pc 0xe767e libart.so (BuildId: b4ba4554d0e918127f6537060375c4bf)
#57 pc 0xc5a989bc
#58 pc 0x15d585 libunity.so (PlayerLoop()) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#59 pc 0xe68afe libunity.so (__ashldi3) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#60 pc 0xe68b06 libunity.so (__ashldi3) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#61 pc 0x24bc01 libunity.so (AndroidAssetPacks::AssetPackManager::UpdateCoreAssetPacksStatus()) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#62 pc 0xe670ff libunity.so (__ashldi3) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)
#63 pc 0xe1bd0e libunity.so (__ashldi3) (BuildId: dec0a910f7ff1ebe110ef9e2b3038088c9e67df1)`

**Comment by AlmostMatt** [comment] 2023-08-11 17:58
I do not see any references to firebase code in those stack traces. Most of the classes and functions mentioned are Unity built-ins
```
- null pointer dereference
- ScriptingInvocation::Invoke
- MonoBehaviour::CallUpdateMethod(int)
- NavMeshManager::Update()
- Scripting::UnityEngine::SendMouseEventsProxy::DoSendMouseEvents(int, ScriptingExceptionPtr*)
- PhysicsManager2D::InterpolateBodies()
- vulkan.adreno.so
- ManagedTempMemScope::ManagedTempMemScope(bool)
- BaseBehaviourManager::CommonUpdate<BehaviourManager>()
...
```

Based on just this, there is not enough information for us to determine the cause of the crash. It might be unique to your project, or it might be an issue with Unity itself. If a Unity built-in method is encountering a null pointer, then it is likely that some game object or asset is unexpectedly null.

For now I will close this issue as it is not clear what is the cause of the crash and there is not much we can do to help.
If you are able to reproduce the crash or further narrow down the problematic code, then feel free to reopen this issue.

**Closed** 2023-08-11 17:58 UTC
Labels: api: crashlytics, needs-attention, type: question
