### ISSUE TITLE
[Bug] Firebase Analytics duplicate events in BigQuery

### ISSUE THREAD

**Issue by dudu-1993** [firebase/firebase-unity-sdk#425] opened 2022-07-28 09:23 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.5f1
  * Firebase Unity SDK version: 9.2.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Analytics
  * Other Firebase Components in use: analytics, app, crashlytics, dynamic-links, messaging, remote-config
  * Additional SDKs you are using: not relevant
  * Platform you are using the Unity editor on: Mac, Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: Mono and IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: open-source

### [REQUIRED] Please describe the issue here:
-- Android Device Log
2022-07-28 16:19:28.165 30982-7032/? V/FA: Activity resumed, time: 868720739
2022-07-28 16:19:30.600 28578-7044/? V/FA-SVC: Logging event: origin=app,name=share_file,params=Bundle[{t***d=6*****b, c***uid=1***0, mime_type=i***g, ga_event_origin(_o)=app, ga_screen_class(_sc)=0***5, ga_screen_id(_si)=-8285458101526925147, ga_screen(_sn)=G***bby, space_tags=[T**W], space_id=0**5}]
2022-07-28 16:19:30.625 28578-7044/? V/FA-SVC: Upload scheduled in approximately ms: 500
2022-07-28 16:19:30.625 28578-7044/? V/FA-SVC: Unscheduling upload
2022-07-28 16:19:30.630 28578-7044/? V/FA-SVC: Scheduling upload, millis: 500
2022-07-28 16:19:30.632 28578-7044/? V/FA-SVC: Background event processing time, ms: 33
2022-07-28 16:19:31.132 28578-7044/? V/FA-SVC: Unscheduling upload
2022-07-28 16:19:31.143 28578-7044/? V/FA-SVC: Starting upload from DelayedRunnable
2022-07-28 16:19:31.163 28578-7044/? V/FA-SVC: Checking account type status for ad personalization signals
2022-07-28 16:19:31.197 28578-7044/? V/FA-SVC: Saving bundle, size: 845
2022-07-28 16:19:31.213 28578-7044/? D/FA-SVC: Uploading events. Elapsed time since last upload attempt (ms): 523
2022-07-28 16:19:31.222 28578-7044/? V/FA-SVC: Uploading data. app, uncompressed size, data: com.****.****.***.***, 820, 
 { ... }
2022-07-28 16:19:31.222 28578-7044/? V/FA-SVC: Not stopping services. fetch, network, upload: false, true, false
2022-07-28 16:19:31.228 28578-7122/? V/FA-SVC: Uploading data. size: 729
2022-07-28 16:19:31.253 28578-7044/? V/FA-SVC: Upload scheduled in approximately ms: 3599989
2022-07-28 16:19:31.253 28578-7044/? V/FA-SVC: Unscheduling upload
2022-07-28 16:19:31.259 28578-7044/? V/FA-SVC: Scheduling upload, millis: 3599989
2022-07-28 16:19:31.261 28578-7044/? V/FA-SVC: Successful upload. Got network response. code, size: 204, 0
2022-07-28 16:19:31.272 28578-7044/? V/FA-SVC: Nothing to upload or uploading impossible
2022-07-28 16:19:31.272 28578-7044/? V/FA-SVC: Unscheduling upload
2022-07-28 16:19:31.280 28578-7044/? V/FA-SVC: Stopping uploading service(s)

#### Steps to reproduce:
I have connected the app to Debug View in firebase to confirm that the application is only sent once, but the event result in bigquery still duplicate.

Steps :
1. After application log a custom analytics event by the function of Firebase.Analytics.FirebaseAnalytics.LogEvent.
2. The event in bigquery will duplicate, maybe duplicate twice, maybe more.
All parameters in events have the same value, include event_timestamp, event_server_timestamp_offset, event_previous_timestamp , event_params. (see more in attach file)
For example:
01 event_timestamp: 1649085072770002/ event_server_timestamp_offset: 1573255 /event_previous_timestamp:1649084664275002
02 event_timestamp: 1649085072770002/ event_server_timestamp_offset: 1573255 /event_previous_timestamp:1649084664275002
03 (same as above)
04 (same as above)
...

#### Relevant Code:

        public void SendEvent(string eventName, IDictionary<string, object> parameters)
        {
            ...
            FirebaseA
![debugview01](https://user-images.githubusercontent.com/110159405/181477839-81d420a9-7476-4aa4-a6d4-544ffeca67c4.PNG)
nalytics.LogEvent(eventName, parameterList.ToArray());
        }
![big01](https://user-images.githubusercontent.com/110159405/181467884-e71a7935-8bdf-4b12-a0a7-db80b53ef516.PNG)

**Comment by paulinon** [comment] 2022-07-28 12:17
Hi @dudu-1993,

Based on the information you provided, the cause of the issue seems to point to BigQuery rather than the SDK, given that the event is sent once in your device logs. With this, you may redirect this to more suitable support channels such as the [Google Analytics Help Center](https://support.google.com/analytics#topic=9143232) or the [Google Analytics Help Community](https://support.google.com/analytics/community). That being said, I'll be closing this for now.

**Closed by paulinon** 2022-07-28 12:17 UTC
Labels: api: analytics, type: question
