### ISSUE TITLE
Firestore SDK doesn't build on Apple Silicon (pointer misalignment during linking)

### ISSUE THREAD

**Issue by aroman** [firebase/firebase-unity-sdk#83] opened 2021-11-02 23:17 UTC
The actual compile step works fine, but the linker throws errors when linking the main FirebaseCppApp on Apple ARM64.

Note #1: building the full SDK directly from the `firebase-cpp-sdk` works fine, including firebase. it just seems to be an issue building here

Note #2: simply excluding the Firestore SDK from `CMakeLists.txt` allows firebase-unity to build.

Output from `sh build_macos.sh`:

```
[100%] Linking CXX shared library FirebaseCppApp-8_5_0.bundle
ld: warning: pointer not aligned at address 0x134776A (__ZN8firebase9firestore34firestore_client_NoDocument_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(maybe_document.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13477C1 (__ZN8firebase9firestore39firestore_client_UnknownDocument_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(maybe_document.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347835 (__ZN8firebase9firestore37firestore_client_MaybeDocument_fieldsE + 79 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(maybe_document.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13477FB (__ZN8firebase9firestore37firestore_client_MaybeDocument_fieldsE + 21 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(maybe_document.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13478E3 (__ZN8firebase9firestore34firestore_client_WriteBatch_fieldsE + 108 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(mutation.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13478C6 (__ZN8firebase9firestore34firestore_client_WriteBatch_fieldsE + 79 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(mutation.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13478A9 (__ZN8firebase9firestore34firestore_client_WriteBatch_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(mutation.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13479CB (__ZN8firebase9firestore30firestore_client_Target_fieldsE + 195 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(target.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13479AE (__ZN8firebase9firestore30firestore_client_Target_fieldsE + 166 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(target.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347991 (__ZN8firebase9firestore30firestore_client_Target_fieldsE + 137 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(target.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x134793A (__ZN8firebase9firestore30firestore_client_Target_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(target.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347A3F (__ZN8firebase9firestore36firestore_client_TargetGlobal_fieldsE + 79 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(target.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347AB3 (__ZN8firebase9firestore29firestore_BundledQuery_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(bundle.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347B27 (__ZN8firebase9firestore27firestore_NamedQuery_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(bundle.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347B9B (__ZN8firebase9firestore40firestore_BundledDocumentMetadata_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(bundle.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347CF7 (__ZN8firebase9firestore30firestore_BundleElement_fieldsE + 79 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(bundle.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347CDA (__ZN8firebase9firestore30firestore_BundleElement_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(bundle.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347CBD (__ZN8firebase9firestore30firestore_BundleElement_fieldsE + 21 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(bundle.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347D6B (__ZN8firebase9firestore39google_firestore_v1_Precondition_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(common.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347DA5 (__ZN8firebase9firestore54google_firestore_v1_TransactionOptions_ReadOnly_fieldsE + 21 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(common.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347DDF (__ZN8firebase9firestore45google_firestore_v1_TransactionOptions_fieldsE + 21 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(common.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347E53 (__ZN8firebase9firestore47google_firestore_v1_Document_FieldsEntry_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(document.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347EC7 (__ZN8firebase9firestore35google_firestore_v1_Document_fieldsE + 79 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(document.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347EAA (__ZN8firebase9firestore35google_firestore_v1_Document_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(document.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347FE9 (__ZN8firebase9firestore32google_firestore_v1_Value_fieldsE + 224 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(document.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347FAF (__ZN8firebase9firestore32google_firestore_v1_Value_fieldsE + 166 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(document.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1347F92 (__ZN8firebase9firestore32google_firestore_v1_Value_fieldsE + 137 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(document.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x134807A (__ZN8firebase9firestore35google_firestore_v1_MapValue_fieldsE + 21 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(document.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x134810B (__ZN8firebase9firestore47google_firestore_v1_MapValue_FieldsEntry_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(document.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348162 (__ZN8firebase9firestore45google_firestore_v1_GetDocumentRequest_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13482A1 (__ZN8firebase9firestore47google_firestore_v1_ListDocumentsRequest_fieldsE + 224 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348267 (__ZN8firebase9firestore47google_firestore_v1_ListDocumentsRequest_fieldsE + 166 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13483C3 (__ZN8firebase9firestore48google_firestore_v1_CreateDocumentRequest_fieldsE + 137 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13483A6 (__ZN8firebase9firestore48google_firestore_v1_CreateDocumentRequest_fieldsE + 108 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348437 (__ZN8firebase9firestore48google_firestore_v1_UpdateDocumentRequest_fieldsE + 79 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x134841A (__ZN8firebase9firestore48google_firestore_v1_UpdateDocumentRequest_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13483FD (__ZN8firebase9firestore48google_firestore_v1_UpdateDocumentRequest_fieldsE + 21 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13484AB (__ZN8firebase9firestore48google_firestore_v1_DeleteDocumentRequest_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348576 (__ZN8firebase9firestore51google_firestore_v1_BatchGetDocumentsRequest_fieldsE + 166 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348559 (__ZN8firebase9firestore51google_firestore_v1_BatchGetDocumentsRequest_fieldsE + 137 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x134851F (__ZN8firebase9firestore51google_firestore_v1_BatchGetDocumentsRequest_fieldsE + 79 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348607 (__ZN8firebase9firestore52google_firestore_v1_BatchGetDocumentsResponse_fieldsE + 108 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x134865E (__ZN8firebase9firestore50google_firestore_v1_BeginTransactionRequest_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13486B5 (__ZN8firebase9firestore40google_firestore_v1_CommitRequest_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348729 (__ZN8firebase9firestore41google_firestore_v1_CommitResponse_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13487D7 (__ZN8firebase9firestore42google_firestore_v1_RunQueryRequest_fieldsE + 137 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13487BA (__ZN8firebase9firestore42google_firestore_v1_RunQueryRequest_fieldsE + 108 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x134884B (__ZN8firebase9firestore43google_firestore_v1_RunQueryResponse_fieldsE + 79 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348811 (__ZN8firebase9firestore43google_firestore_v1_RunQueryResponse_fieldsE + 21 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348916 (__ZN8firebase9firestore39google_firestore_v1_WriteRequest_fieldsE + 137 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13489A7 (__ZN8firebase9firestore40google_firestore_v1_WriteResponse_fieldsE + 108 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x134898A (__ZN8firebase9firestore40google_firestore_v1_WriteResponse_fieldsE + 79 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13489FE (__ZN8firebase9firestore33google_firestore_v1_Target_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13489E1 (__ZN8firebase9firestore33google_firestore_v1_Target_fieldsE + 21 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348B03 (__ZN8firebase9firestore40google_firestore_v1_ListenRequest_fieldsE + 108 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348AC9 (__ZN8firebase9firestore40google_firestore_v1_ListenRequest_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348BB1 (__ZN8firebase9firestore39google_firestore_v1_TargetChange_fieldsE + 137 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348B77 (__ZN8firebase9firestore39google_firestore_v1_TargetChange_fieldsE + 79 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348C5F (__ZN8firebase9firestore41google_firestore_v1_ListenResponse_fieldsE + 137 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348C42 (__ZN8firebase9firestore41google_firestore_v1_ListenResponse_fieldsE + 108 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348C25 (__ZN8firebase9firestore41google_firestore_v1_ListenResponse_fieldsE + 79 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348BEB (__ZN8firebase9firestore41google_firestore_v1_ListenResponse_fieldsE + 21 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348CB6 (__ZN8firebase9firestore45google_firestore_v1_Target_QueryTarget_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(firestore.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348D47 (__ZN8firebase9firestore49google_firestore_v1_StructuredQuery_Filter_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(query.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348D2A (__ZN8firebase9firestore49google_firestore_v1_StructuredQuery_Filter_fieldsE + 21 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(query.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348D9E (__ZN8firebase9firestore48google_firestore_v1_StructuredQuery_Order_fieldsE + 21 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(query.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348DF5 (__ZN8firebase9firestore33google_firestore_v1_Cursor_fieldsE + 21 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(query.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348F17 (__ZN8firebase9firestore42google_firestore_v1_StructuredQuery_fieldsE + 224 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(query.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348EFA (__ZN8firebase9firestore42google_firestore_v1_StructuredQuery_fieldsE + 195 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(query.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348EA3 (__ZN8firebase9firestore42google_firestore_v1_StructuredQuery_fieldsE + 108 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(query.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348E86 (__ZN8firebase9firestore42google_firestore_v1_StructuredQuery_fieldsE + 79 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(query.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348E69 (__ZN8firebase9firestore42google_firestore_v1_StructuredQuery_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(query.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348F6E (__ZN8firebase9firestore58google_firestore_v1_StructuredQuery_CompositeFilter_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(query.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1348FE2 (__ZN8firebase9firestore54google_firestore_v1_StructuredQuery_FieldFilter_fieldsE + 79 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(query.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1349039 (__ZN8firebase9firestore54google_firestore_v1_StructuredQuery_UnaryFilter_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(query.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x134915B (__ZN8firebase9firestore59google_firestore_v1_DocumentTransform_FieldTransform_fieldsE + 166 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(write.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x134913E (__ZN8firebase9firestore59google_firestore_v1_DocumentTransform_FieldTransform_fieldsE + 137 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(write.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1349121 (__ZN8firebase9firestore59google_firestore_v1_DocumentTransform_FieldTransform_fieldsE + 108 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(write.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1349243 (__ZN8firebase9firestore32google_firestore_v1_Write_fieldsE + 166 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(write.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1349226 (__ZN8firebase9firestore32google_firestore_v1_Write_fieldsE + 137 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(write.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1349209 (__ZN8firebase9firestore32google_firestore_v1_Write_fieldsE + 108 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(write.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13491B2 (__ZN8firebase9firestore32google_firestore_v1_Write_fieldsE + 21 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(write.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13492B7 (__ZN8firebase9firestore38google_firestore_v1_WriteResult_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(write.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x134929A (__ZN8firebase9firestore38google_firestore_v1_WriteResult_fieldsE + 21 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(write.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13492F1 (__ZN8firebase9firestore41google_firestore_v1_DocumentChange_fieldsE + 21 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(write.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1349382 (__ZN8firebase9firestore41google_firestore_v1_DocumentDelete_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(write.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1349413 (__ZN8firebase9firestore41google_firestore_v1_DocumentRemove_fieldsE + 79 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(write.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x1349487 (__ZN8firebase9firestore24google_rpc_Status_fieldsE + 79 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(status.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13494DE (__ZN8firebase9firestore41google_protobuf_Struct_FieldsEntry_fieldsE + 50 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(struct.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13495E3 (__ZN8firebase9firestore28google_protobuf_Value_fieldsE + 166 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(struct.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x13495C6 (__ZN8firebase9firestore28google_protobuf_Value_fieldsE + 137 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(struct.nanopb.cc.o))
ld: warning: pointer not aligned at address 0x134961D (__ZN8firebase9firestore32google_protobuf_ListValue_fieldsE + 21 from bin/external/src/firestore-build/Firestore/Protos/libfirestore_protos_nanopb.a(struct.nanopb.cc.o))
ld: unaligned pointer(s) for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dconeybe** [comment] 2021-11-03 05:29
This affects the C++ SDK too: https://github.com/firebase/firebase-cpp-sdk/issues/712. I'm going to close this issue as a duplicate of the one in the C++ SDK since the investigation progress is being recorded there.

**Closed by dconeybe** 2021-11-03 05:29 UTC
Labels: bug
