### ISSUE TITLE
in_app_purchases on iOS not logging in Firebase 

### ISSUE THREAD

**Issue by estellise-yukihime** [firebase/firebase-unity-sdk#260] opened 2022-04-27 12:44 UTC
The problem is exactly as the title.

This it the graph for the past few weeks
Blue = iOS
Orange = Android

![image](https://user-images.githubusercontent.com/44573967/165519985-fafeebc7-7400-4ec9-a5ec-dee762bae2c2.png)

I have re-setup the Firebase SDK, set IS_ANALYTICS_ENABLED to YES, and FirebaseAnalytics.SetAnalyticsCollectionEnabled to TRUE and still not logging the in_app_purchases event in Firebase.

Unity v2021.2.5f1
Firebase SDK v870

**Comment by DellaBitta** [comment] 2022-07-19 14:07
Hi @estellise-yukihime,

I recommend reaching out to [Firebase Support](https://firebase.google.com/support/troubleshooter/contact) who can help you with any sort of project configuration in the backend which might affect in app purchase analytics.  `FIREBASE_ANALYTICS_COLLECTION_ENABLED` is actually read by the Firebase iOS Analytics SDK which the Unity SDK wraps, so the behavior affected by that flag is handled by a different SDK.  The support team can help determine the cause of this issue.

I'm going to close this issue for now.  If you continue to have an issue please re-open a new bug.  We now have Issue Templates which help us collect information that we'd need to help debug the problem.

Thanks!

**Closed** 2022-07-19 14:07 UTC
Labels: api: analytics, type: question
