### ISSUE TITLE
[Bug] FirebaseCore_Privacy.bundle not found

### ISSUE THREAD

**Issue by Nathanael-MZ** [firebase/firebase-unity-sdk#982] opened 2024-04-03 19:59 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.3.13f1
  * Firebase Unity SDK version: 11.8.1
  * Source you installed the SDK: unitypackage
  * Problematic Firebase Component: all
  * Other Firebase Components in use: Analytics, Messaging 
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: website

### [REQUIRED] Please describe the issue here:
iOS build fails with the following error message.
```
INFO: - 04/01/2024 05:01:24 PM - /bin/sh -c /Users/jenkins.svc/Library/Developer/Xcode/DerivedData/Unity-iPhone-cxacfxttnraokwbsykyzgvjohape/Build/Intermediates.noindex/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/Script-283F2945DF57988331C2D4C1.sh
ERROR: - 04/01/2024 05:01:24 PM - error: Resource "/Users/jenkins.svc/Library/Developer/Xcode/DerivedData/Unity-iPhone-cxacfxttnraokwbsykyzgvjohape/Build/Products/Release-iphoneos/FirebaseCore/FirebaseCore_Privacy.bundle" not found. Run 'pod install' to update the copy resources script.
```

#### Steps to reproduce:

1. Build an xcode project via Unity
1. Build the xcode project and sign

**Comment by a-maurice** [comment] 2024-04-04 17:47
Hi @Nathanael-MZ 

Unfortunately we haven't been able to reproduce this on our end.  What version of XCode are you using?  I see the error that you posted suggests running `pod install`, have you tried doing so from the directory that you created the xcode project in?  Finally, if you can share your Podfile.lock, that would help indicate what dependencies are being included in your project.

**Comment by Nathanael-MZ** [comment] 2024-04-04 17:57
We are running XCode 15.0.1. The `FirebaseCoreInternal_Privacy.bundle` is in the build folder but we still get the file not found error.

`PODS:
  - Firebase/Analytics (10.11.0):
    - Firebase/Core
  - Firebase/Core (10.11.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.11.0)
  - Firebase/CoreOnly (10.11.0):
    - FirebaseCore (= 10.11.0)
  - FirebaseAnalytics (10.11.0):
    - FirebaseAnalytics/AdIdSupport (= 10.11.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.11.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.11.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - FirebaseCore (10.11.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Logger (~> 7.8)
  - FirebaseCoreInternal (10.23.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseInstallations (10.23.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - GoogleAppMeasurement (10.11.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.11.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.11.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.11.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.11.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - GoogleUtilities/AppDelegateSwizzler (7.13.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
    - GoogleUtilities/Privacy
  - GoogleUtilities/Environment (7.13.0):
    - GoogleUtilities/Privacy
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.13.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Privacy
  - GoogleUtilities/MethodSwizzler (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/Network (7.13.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Privacy
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.13.0)":
    - GoogleUtilities/Privacy
  - GoogleUtilities/Privacy (7.13.0)
  - GoogleUtilities/Reachability (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/UserDefaults (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - nanopb (2.30909.1):
    - nanopb/decode (= 2.30909.1)
    - nanopb/encode (= 2.30909.1)
  - nanopb/decode (2.30909.1)
  - nanopb/encode (2.30909.1)
  - PromisesObjC (2.4.0)

DEPENDENCIES:
  - Firebase/Analytics (= 10.11.0)
  - Firebase/Core (= 10.11.0)

SPEC REPOS:
  trunk:
    - Firebase
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreInternal
    - FirebaseInstallations
    - GoogleAppMeasurement
    - GoogleUtilities
    - nanopb
    - PromisesObjC

SPEC CHECKSUMS:
  Firebase: 31d9575c124839fb5abc0db6d39511cc1dab1b85
  FirebaseAnalytics: 6c6bf99e8854475bf1fa342028841be8ecd236da
  FirebaseCore: 62fd4d549f5e3f3bd52b7998721c5fa0557fb355
  FirebaseCoreInternal: 6a292e6f0bece1243a737e81556e56e5e19282e3
  FirebaseInstallations: 42d6ead4605d6eafb3b6683674e80e18eb6f2c35
  GoogleAppMeasurement: d3dabccdb336fc0ae44b633c8abaa26559893cd9
  GoogleUtilities: d053d902a8edaa9904e1bd00c37535385b8ed152
  nanopb: d4d75c12cd1316f4a64e3c6963f879ecd4b5e0d5
  PromisesObjC: f5707f49cb48b9636751c5b2e7d227e43fba9f47

PODFILE CHECKSUM: ec5832c86df4f2fd4c142aa4e8314ec76261be2d

COCOAPODS: 1.15.2
`

**Comment by a-maurice** [comment] 2024-04-04 19:09
Thanks.  Discussing this with the Firebase iOS team, the issue is likely caused by the recent changes on the Apple side around Privacy Manifests, info here: https://developer.apple.com/support/third-party-SDK-requirements  The Firebase iOS SDK added the privacy manifests in [10.22.0](https://firebase.google.com/support/release-notes/ios#version_10220_-_march_4_2024), which for the Unity SDK was the recent [11.8.0 release](https://github.com/firebase/firebase-unity-sdk/releases/tag/v11.8.0).  It could be that XCode is looking for the privacy manifest, and failing to find it because you have 10.11.0 of the FirebaseCore pod (though I didn't think they were enforcing this until May), so one potential fix would be to update the versions you are using.

Another possibility, in the Podfile.lock it is getting a couple of Firebase internal pods at 10.23.0, instead of 10.11.0.  Normally, this shouldn't cause issues, but possibly it is because of the privacy manifest changes.  So what you can try is pinning FirebaseCoreInternal and FirebaseInstallations at 10.11.0 as well.  You can do this by either editing the Podfile that is generated by the Unity build, or in the Unity project, edit your Assets/Firebase/Editor/AppDependencies.xml, and add those pods with those version numbers, which will cause the Podfile to be generated with them.  If you are using the Firebase SDK through a Unity package such that you don't have that file, you can add one, copying the format from the one that should be in your packages, and then add the lines.

**Comment by ncooke3** [comment] 2024-04-05 15:41
Hi @Nathanael-MZ, could you confirm that you are opening the `.xcworkspace` file rather than the `.xcodeproj` file?

**Comment by Nathanael-MZ** [comment] 2024-04-05 19:05
> Hi @Nathanael-MZ, could you confirm that you are opening the `.xcworkspace` file rather than the `.xcodeproj` file?

Yes, we are using the .xcodeproj file

**Comment by ncooke3** [comment] 2024-04-05 19:47
@Nathanael-MZ, try closing the window with the `.xcodeproj` and re-opening the `.xcworkspace`. Running `pod install` generates an `.xcworkspace`, and that should be used to develop rather than the `.xcodeproj`.

**Comment by Nathanael-MZ** [comment] 2024-04-05 19:53
Sorry, I was wrong. We do the pod install, then build with the xcworkspace.

**Comment by ncooke3** [comment] 2024-04-05 20:20
No worries. That's interesting. I was able to reproduce the issue when building the `.xcodeproj`, but not when when building `.xcworkspace`. There's definitely something else going on then. Could you share your Podfile? Feel free to redact target names and what not. I'd like to see the structure and use it to attempt to reproduce in a simple app.

**Comment by supergardener** [comment] 2024-04-07 06:24
@a-maurice Thank you for the detailed information. Considering the recent changes in Apple's Privacy Manifests, it seems plausible that the issues stem from compatibility with older versions of Firebase iOS SDK. Could you please confirm if there have been any recent updates to the Firebase Unity SDK that might address these concerns? We're eager to resolve the issue and ensure compatibility with the latest requirements from Apple.

**Comment by Nathanael-MZ** [comment] 2024-04-09 22:18
We are using the latest Firebase Unity SDK 11.8 and we tried upgrading to XCode 15.3.
Podfile:
```
source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics', '10.22.0'
  pod 'Firebase/Core', '10.22.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
```
Podefile.lock:
```
PODS:
  - Firebase/Analytics (10.22.0):
    - Firebase/Core
  - Firebase/Core (10.22.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.22.0)
  - Firebase/CoreOnly (10.22.0):
    - FirebaseCore (= 10.22.0)
  - FirebaseAnalytics (10.22.0):
    - FirebaseAnalytics/AdIdSupport (= 10.22.0)
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (10.22.0):
    - FirebaseCore (~> 10.0)
    - FirebaseInstallations (~> 10.0)
    - GoogleAppMeasurement (= 10.22.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - FirebaseCore (10.22.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.12)
    - GoogleUtilities/Logger (~> 7.12)
  - FirebaseCoreInternal (10.24.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseInstallations (10.24.0):
    - FirebaseCore (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/UserDefaults (~> 7.8)
    - PromisesObjC (~> 2.1)
  - GoogleAppMeasurement (10.22.0):
    - GoogleAppMeasurement/AdIdSupport (= 10.22.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (10.22.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 10.22.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (10.22.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.11)
    - GoogleUtilities/MethodSwizzler (~> 7.11)
    - GoogleUtilities/Network (~> 7.11)
    - "GoogleUtilities/NSData+zlib (~> 7.11)"
    - nanopb (< 2.30911.0, >= 2.30908.0)
  - GoogleUtilities/AppDelegateSwizzler (7.13.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
    - GoogleUtilities/Privacy
  - GoogleUtilities/Environment (7.13.0):
    - GoogleUtilities/Privacy
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.13.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Privacy
  - GoogleUtilities/MethodSwizzler (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/Network (7.13.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Privacy
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.13.0)":
    - GoogleUtilities/Privacy
  - GoogleUtilities/Privacy (7.13.0)
  - GoogleUtilities/Reachability (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/UserDefaults (7.13.0):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - nanopb (2.30910.0):
    - nanopb/decode (= 2.30910.0)
    - nanopb/encode (= 2.30910.0)
  - nanopb/decode (2.30910.0)
  - nanopb/encode (2.30910.0)
  - PromisesObjC (2.4.0)

DEPENDENCIES:
  - Firebase/Analytics (= 10.22.0)
  - Firebase/Core (= 10.22.0)

SPEC REPOS:
  trunk:
    - Firebase
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreInternal
    - FirebaseInstallations
    - GoogleAppMeasurement
    - GoogleUtilities
    - nanopb
    - PromisesObjC

SPEC CHECKSUMS:
  Firebase: 797fd7297b7e1be954432743a0b3f90038e45a71
  FirebaseAnalytics: 8d0ff929c63b7f72260f332b86ccf569776b75d3
  FirebaseCore: 0326ec9b05fbed8f8716cddbf0e36894a13837f7
  FirebaseCoreInternal: bcb5acffd4ea05e12a783ecf835f2210ce3dc6af
  FirebaseInstallations: 8f581fca6478a50705d2bd2abd66d306e0f5736e
  GoogleAppMeasurement: ccefe3eac9b0aa27f96066809fb1a7fe4b462626
  GoogleUtilities: d053d902a8edaa9904e1bd00c37535385b8ed152
  nanopb: 438bc412db1928dac798aa6fd75726007be04262
  PromisesObjC: f5707f49cb48b9636751c5b2e7d227e43fba9f47

PODFILE CHECKSUM: 4518c8a121026ee4da9db61eba851098c18bdd48

COCOAPODS: 1.15.2

```
[build.log](https://github.com/firebase/firebase-unity-sdk/files/14924380/build.log)

**Comment by a-maurice** [comment] 2024-04-11 17:22
I've tried reproducing this with the same Unity version, and using older Cocoapods to force a mismatch of the versions, and still haven't had any luck on my end.  My best guess is that something is preventing the pods from being put into the working directory, but no idea what that might be.

**Comment by andymillermz** [comment] 2024-04-11 20:49
Hey folks - we figured out the issue here.

Somehow these recent bundle changes seems to now break with the xcode build flags we set.

We were using `CONFIGURATION_BUILD_DIR` to set the directory where all build steps would happen - this includes all those xcode build and intermediate steps that happen in the DerivedData location.

Unsure when that changed but it seems either that flag is no longer properly respected when building an xcode workspace. It still behaves the same when building an xcode project file alone.

When running xcodebuild with `-derivedDataPath` and `-archivePath` flags we can now get full builds along with keeping all build files and data under our build directory.

Appreciate the help 👍

**Comment by a-maurice** [comment] 2024-04-11 21:31
Great that you were able to track down the issue, thanks for following up.  Searching for issues with Cocoapods and `CONFIGURATION_BUILD_DIR` I do see a few issues, though naturally all different enough to make it hard to find without already knowing that is the problem.  We'll aim to keep an eye out for that field in the future for similar types of issues.

**Closed by a-maurice** 2024-04-11 21:31 UTC
Labels: api: core, needs-attention, type: question
